(()=>{'use strict';

const AUTO='melon_auto_v5';
const SLOT='melon_slot_v5_';
const START_YEAR=2026;
const WEEKS=52;
const MANIFEST='./data/database.json';

const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const defs=[
  ['reputation','Reputacja','greenbar'],
  ['activity','Aktywność','bluebar'],
  ['popularity','Rozpoznawalność',''],
  ['controversy','Kontrowersyjność',''],
  ['trust','Zaufanie','greenbar']
];
const archetypes={
  lurker:{activity:-8,trust:3,controversy:-5,popularity:-2,reputation:2},
  regular:{activity:4,trust:3,reputation:3},
  memer:{activity:5,popularity:6,controversy:2},
  debater:{activity:6,controversy:6,reputation:1},
  helper:{trust:8,reputation:6,activity:2}
};
const starts={
  fresh:{melons:100,popularity:8},
  known:{melons:140,popularity:18,reputation:8},
  veteran:{melons:180,popularity:28,reputation:12,trust:10}
};
const diffs={easy:{p:1.2,n:.8},normal:{p:1,n:1},hard:{p:.9,n:1.25}};
const DEFAULT_LEVELING={baseXp:300,growthPerLevel:75,maxLevel:50};

let state=load(AUTO);
let events=[];
let autoEvents=[];
let serverUsers=[];
let oneTimeIds=new Set();
let meta={
  databaseVersion:'-',packs:[],automaticPacks:[],automaticEventChance:.28,usersFile:'users.txt',
  oneTimeEventIds:[],leveling:{...DEFAULT_LEVELING},
  decisionPointDefaults:{
    positive:{plusChanceMin:65,plusChanceMax:85,minusMultiplierMin:.45,minusMultiplierMax:.75,plusMultiplierMin:.9,plusMultiplierMax:1.2},
    negative:{plusChanceMin:20,plusChanceMax:45,minusMultiplierMin:.9,minusMultiplierMax:1.25,plusMultiplierMin:.4,plusMultiplierMax:.7}
  }
};
let ready=false,current=null,galaOpening=false;

function rng(){try{if(globalThis.crypto?.getRandomValues){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}}catch{}return Math.random()}
function rnd(a,b){return a+rng()*(b-a)}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(s){return String(s||'').trim().toLocaleLowerCase('pl')}
function load(k){try{return JSON.parse(localStorage.getItem(k))}catch{return null}}
function save(){if(state)localStorage.setItem(AUTO,JSON.stringify(state))}
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2600)}
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h>>>0}
function hashRange(seed,min,max,shift=0){min=Number(min);max=Number(max);if(!Number.isFinite(min))min=0;if(!Number.isFinite(max))max=min;if(max<min)[min,max]=[max,min];const span=max-min;if(span<=0)return min;return min+(((seed>>>shift)&0xffff)/0xffff)*span}

function leveling(){return{...DEFAULT_LEVELING,...(meta.leveling||{})}}
function xpCostForLevel(level){const c=leveling(),l=Math.max(1,Math.floor(Number(level)||1));return Math.max(1,Math.round(Number(c.baseXp||300)+(l-1)*Number(c.growthPerLevel||75)))}
function xpRequiredForLevel(level){const c=leveling(),l=Math.max(1,Math.floor(Number(level)||1)),n=l-1;return Math.max(0,Math.round(n*Number(c.baseXp||300)+(Number(c.growthPerLevel||75)*n*(n-1))/2))}
function levelForScore(score){const c=leveling(),max=Math.max(2,Math.floor(Number(c.maxLevel||50))),s=Math.max(0,Number(score)||0);let lo=1,hi=max;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(xpRequiredForLevel(mid)<=s)lo=mid;else hi=mid-1}return lo}
function xpProgress(score){const level=levelForScore(score),start=xpRequiredForLevel(level),next=xpRequiredForLevel(level+1),inside=Math.max(0,Math.round((Number(score)||0)-start)),need=Math.max(1,next-start);return{level,start,next,inside,need,percent:clamp(Math.round(inside/need*100),0,100)}}

function role(s){if(s.level>=10&&s.reputation>=65)return'LEGENDA';if(s.trust>=75&&s.level>=6)return'AUTORYTET';if(s.popularity>=70)return'CELEBRYTA';if(s.controversy>=72)return'KONTROWERSYJNY';if(s.level>=5)return'WETERAN';if(s.level>=3)return'STAŁY BYWALEC';return'NOWICJUSZ'}
function normalizeState(s){
  for(const k of['reputation','activity','popularity','controversy','trust'])s[k]=clamp(Number(s[k]??50),0,100);
  s.score=Math.max(0,Math.round(Number(s.score||0)));s.melons=Math.max(0,Math.round(Number(s.melons||0)));
  s.level=levelForScore(s.score);s.bestLevel=Math.max(Number(s.bestLevel||1),s.level);s.startYear=START_YEAR;
  s.eventCount=Math.max(0,Number(s.eventCount||0));s.autoEventCount=Math.max(0,Number(s.autoEventCount||0));s.goodChoices=Math.max(0,Number(s.goodChoices||0));s.badChoices=Math.max(0,Number(s.badChoices||0));
  if(!Array.isArray(s.history))s.history=[];if(!Array.isArray(s.completedOneTimeEvents))s.completedOneTimeEvents=[];
  if(!s.galas||typeof s.galas!=='object'||Array.isArray(s.galas))s.galas={};
  if(!Array.isArray(s.galaNominationCycleUsed))s.galaNominationCycleUsed=[];if(!Array.isArray(s.galaWinnerCycleUsed))s.galaWinnerCycleUsed=[];
  s.role=role(s);s.status=s.ended?(s.ending==='moderator'?'MODERATOR':'ZBANOWANY'):(s.reputation<=12||s.trust<=10?'Na krawędzi bana':s.controversy>=85?'Centrum dramy':'Aktywny');return s
}
function fresh(){const s={nickname:$('nicknameInput').value.trim()||'Użytkownik',archetype:$('archetypeInput').value,startPoint:$('startPointInput').value,difficulty:$('difficultyInput').value,turn:1,score:0,level:1,bestLevel:1,melons:100,streak:0,reputation:50,activity:50,popularity:10,controversy:15,trust:45,eventCount:0,autoEventCount:0,goodChoices:0,badChoices:0,history:[],completedOneTimeEvents:[],ended:false,ending:null,galas:{},galaNominationCycleUsed:[],galaWinnerCycleUsed:[]};Object.assign(s,starts[s.startPoint]||{});for(const[k,v]of Object.entries(archetypes[s.archetype]||{}))s[k]=(s[k]||0)+v;s.score=0;s.level=1;s.bestLevel=1;return normalizeState(s)}
function year(){return START_YEAR+Math.floor((Math.max(1,state?.turn||1)-1)/WEEKS)}
function week(){return((Math.max(1,state?.turn||1)-1)%WEEKS)+1}
function utility(e={}){const w={reputation:1.2,trust:1.3,popularity:.6,activity:.18,controversy:-1.25,score:.045,melons:.03,streak:1.5};return Object.entries(e).reduce((s,[k,v])=>s+(w[k]||0)*(Number(v)||0),0)}

function pointDefaultsFor(outcome){const hardcoded=outcome==='negative'?{plusChanceMin:20,plusChanceMax:45,minusMultiplierMin:.9,minusMultiplierMax:1.25,plusMultiplierMin:.4,plusMultiplierMax:.7}:{plusChanceMin:65,plusChanceMax:85,minusMultiplierMin:.45,minusMultiplierMax:.75,plusMultiplierMin:.9,plusMultiplierMax:1.2};return{...hardcoded,...(meta?.decisionPointDefaults?.[outcome]||{})}}
function normalizeCustomPointChances(raw){if(!Array.isArray(raw)||raw.length<2)return null;const clean=raw.map(x=>({chance:Number(x?.chance),points:Math.trunc(Number(x?.points))})).filter(x=>Number.isFinite(x.chance)&&x.chance>0&&Number.isFinite(x.points));if(clean.length<2)return null;const total=clean.reduce((s,x)=>s+x.chance,0);let out=clean.map(x=>({chance:Math.round(x.chance/total*1000)/10,points:x.points}));const diff=Math.round((100-out.reduce((s,x)=>s+x.chance,0))*10)/10;out[0].chance=Math.round((out[0].chance+diff)*10)/10;return out}
function derivedPointChances(eventId,choice){const custom=normalizeCustomPointChances(choice.pointChances);if(custom)return custom;const outcome=choice.outcome==='negative'?'negative':'positive',cfg=pointDefaultsFor(outcome),seed=hash32(`${eventId}|${choice.label||''}|${outcome}`),base=Math.max(10,Math.abs(Math.trunc(Number(choice.effects?.score)||20))),plusChance=Math.round(hashRange(seed,cfg.plusChanceMin,cfg.plusChanceMax,0)),plusPoints=Math.max(5,Math.round(base*hashRange(seed,cfg.plusMultiplierMin,cfg.plusMultiplierMax,8)/5)*5),minusPoints=-Math.max(5,Math.round(base*hashRange(seed,cfg.minusMultiplierMin,cfg.minusMultiplierMax,16)/5)*5);return[{chance:plusChance,points:plusPoints},{chance:100-plusChance,points:minusPoints}]}
function chanceLabel(chances){return chances.map(x=>`${x.chance}% → ${x.points>0?'+':''}${x.points} PKT`).join('  •  ')}
function rollPointOutcome(chances){let r=rng()*chances.reduce((s,x)=>s+Number(x.chance||0),0);for(const x of chances){r-=Number(x.chance||0);if(r<=0)return x}return chances.at(-1)}
function applyExactScore(points){const p=Math.trunc(Number(points)||0);state.score=Math.max(0,state.score+p);normalizeState(state);return p}

function normEvent(e){e={...e};e.id=e.id||`evt_${Math.random().toString(36).slice(2)}`;e.title=e.title||'Event';e.category=e.category||'EVENT';e.description=e.description||'';e.weight=Math.max(1,Number(e.weight)||1);e.minTurn=Math.max(1,Number(e.minTurn)||1);e.enabled=e.enabled!==false;e.oneTime=e.oneTime===true||oneTimeIds.has(String(e.id));const src=(Array.isArray(e.choices)?e.choices:[]).map(c=>({...c,effects:c?.effects&&typeof c.effects==='object'?c.effects:{}})),sorted=[...src].sort((a,b)=>utility(a.effects)-utility(b.effects));let pos=src.find(c=>c.outcome==='positive')||sorted.at(-1)||{label:'Podejdź rozsądnie',effects:{reputation:5,score:20}},neg=src.find(c=>c.outcome==='negative')||sorted[0]||{label:'Podejmij złą decyzję',effects:{reputation:-5,controversy:7,score:-20}};pos={...pos,outcome:'positive'};neg={...neg,outcome:'negative'};pos.pointChances=derivedPointChances(e.id,pos);neg.pointChances=derivedPointChances(e.id,neg);e.choices=[pos,neg];return e}
function normAuto(e){e={...e};e.id=e.id||`auto_${Math.random().toString(36).slice(2)}`;e.title=e.title||'Losowe zdarzenie';e.category=e.category||'ZDARZENIE LOSOWE';e.description=e.description||'';e.result=e.result||'Zdarzenie kończy się bez twojej decyzji.';e.effects=e.effects&&typeof e.effects==='object'?e.effects:{};e.weight=Math.max(1,Number(e.weight)||1);e.minTurn=Math.max(1,Number(e.minTurn)||1);e.enabled=e.enabled!==false;e.oneTime=e.oneTime===true||oneTimeIds.has(String(e.id));return e}
function parseUsers(t){const seen=new Set(),out=[];for(const raw of String(t).split(/\r?\n/)){const n=raw.trim(),k=key(n);if(!n||n.startsWith('#')||n.startsWith('//')||seen.has(k))continue;seen.add(k);out.push(n)}return out}
function dedupeById(list){const m=new Map();for(const e of list){if(e?.id)m.set(String(e.id),e);else m.set(`anon_${m.size}`,e)}return[...m.values()]}
function syncOneTimeFromHistory(){if(!state)return;const completed=new Set((state.completedOneTimeEvents||[]).map(String)),configured=new Set([...events,...autoEvents].filter(e=>e.oneTime).map(e=>String(e.id)));for(const h of state.history||[])if(configured.has(String(h.eventId)))completed.add(String(h.eventId));state.completedOneTimeEvents=[...completed]}
function markOneTime(e){if(!state||!e?.oneTime)return;const set=new Set((state.completedOneTimeEvents||[]).map(String));set.add(String(e.id));state.completedOneTimeEvents=[...set]}
function completedOneTime(e){return !!e?.oneTime&&(state.completedOneTimeEvents||[]).map(String).includes(String(e.id))}

async function loadDatabase(){ready=false;try{const mr=await fetch(`${MANIFEST}?t=${Date.now()}`,{cache:'no-store'});if(!mr.ok)throw Error(`manifest HTTP ${mr.status}`);meta={...meta,...await mr.json(),leveling:{...DEFAULT_LEVELING,...((await mr.clone?.().json?.())||{})?.leveling}};/* clone fallback above is harmless; real leveling is normalized below */}catch(e){/* second, reliable load below */}
  try{const mr=await fetch(`${MANIFEST}?v714=${Date.now()}`,{cache:'no-store'});if(!mr.ok)throw Error(`manifest HTTP ${mr.status}`);const manifest=await mr.json();meta={...meta,...manifest,leveling:{...DEFAULT_LEVELING,...(manifest.leveling||{})}};oneTimeIds=new Set((meta.oneTimeEventIds||[]).map(String));const loaded=[];for(const p of meta.packs||[]){const r=await fetch(`./data/${p}?v=${encodeURIComponent(meta.databaseVersion||'0')}&t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`${p}: HTTP ${r.status}`);const d=await r.json();if(!Array.isArray(d))throw Error(`${p}: nieprawidłowa baza`);loaded.push(...d)}events=dedupeById(loaded).map(normEvent);const al=[];for(const p of meta.automaticPacks||[]){const r=await fetch(`./data/${p}?v=${encodeURIComponent(meta.databaseVersion||'0')}&t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`${p}: HTTP ${r.status}`);const d=await r.json();if(Array.isArray(d))al.push(...d)}autoEvents=dedupeById(al).map(normAuto);try{const f=meta.usersFile||'users.txt',r=await fetch(`./data/${f}?v=${encodeURIComponent(meta.databaseVersion||'0')}&t=${Date.now()}`,{cache:'no-store'});serverUsers=r.ok?parseUsers(await r.text()):[]}catch{serverUsers=[]}if(state){normalizeState(state);syncOneTimeFromHistory();save()}ready=events.length>0;dbStatus()}catch(e){console.error(e);events=[];autoEvents=[];serverUsers=[];ready=false;dbStatus(e.message)}}
function dbStatus(err=''){const t=ready?`Baza ${meta.databaseVersion||'-'} • ${events.length} eventów • ${autoEvents.length} losowych • ${serverUsers.length} użytkowników`:`Baza eventów niedostępna${err?' • '+err:''}`;for(const id of['dbStatusStart','dbStatusGame']){const e=$(id);if(e){e.textContent=t;e.classList.toggle('db-error',!ready)}}if($('startBtn'))$('startBtn').disabled=!ready}
function summary(e={}){const n={reputation:'REP',activity:'AKT',popularity:'POP',controversy:'KON',trust:'ZAU',melons:'🍉',score:'PKT',streak:'SERIA'},a=Object.entries(e).filter(([,v])=>v).map(([k,v])=>`${n[k]||k} ${v>0?'+':''}${v}`);return a.join(' • ')||'bez zmian'}
function apply(e={}){const d=diffs[state.difficulty]||diffs.normal,out={};for(const[k,raw]of Object.entries(e)){if(k==='score')continue;let v=Number(raw)||0;if(!v)continue;v=Math.round(v*(v>0?d.p:d.n)*rnd(.78,1.28));if(!v)v=raw>0?1:-1;out[k]=v;state[k]=(state[k]||0)+v}normalizeState(state);return out}

function cleanResultText(text=''){let t=String(text).trim();t=t.replace(/\s*Finalnie wychodzisz na tej sytuacji wyraźnie na plus\.?/gi,'').trim();t=t.replace(/^Reakcja na „[^”]+” okazuje się fatalna\.\s*Sytuacja obraca się przeciwko tobie i twoja pozycja na Melonawce wyraźnie cierpi\.?$/i,'').trim();t=t.replace(/^Reagujesz bez dokładania niepotrzebnego zamieszania\.?$/i,'').trim();return t}
const NARRATIVES={
 'DRAMA':{positive:['Nie dokładasz kolejnej iskry do konfliktu. Emocje opadają, a inni zauważają, że potrafisz zachować głowę, kiedy robi się gorąco.','Twoja reakcja ucina część napięcia. Zamiast następnej rundy dramy pojawia się przestrzeń na normalną rozmowę.','Wybierasz rozwiązanie, które nie daje dramie dodatkowego paliwa. To działa lepiej, niż mogło się wydawać.'],negative:['Twoja reakcja działa jak benzyna dolana do ognia. Dyskusja momentalnie robi się bardziej osobista, a twój udział zaczyna być częścią problemu.','Zamiast wygasić konflikt, dokładasz mu nową rundę. Ludzie zapamiętują nie tylko temat, ale też sposób, w jaki w niego wszedłeś.','Sytuacja eskaluje po twojej odpowiedzi. Nawet osoby stojące z boku zaczynają kojarzyć cię z całym zamieszaniem.']},
 'MEMY':{positive:['Trafiasz z wyczuciem w moment i humor społeczności. Reakcje pojawiają się szybko, ale nie przeciągasz żartu ponad jego żywotność.','Żart siada dokładnie tak, jak powinien. Zyskujesz uwagę bez robienia z jednego mema tygodniowego obowiązku.','Wyłapujesz odpowiedni ton i społeczność kupuje ten żart bez większych zastrzeżeń.'],negative:['Żart zaczyna żyć o kilka wiadomości za długo. Zamiast kolejnych reakcji pojawia się zmęczenie i coraz bardziej wymuszona atmosfera.','Próbujesz wycisnąć z mema więcej, niż ma do zaoferowania. Część osób zaczyna reagować bardziej na ciebie niż na sam żart.','Miało być śmiesznie, ale sposób, w jaki ciągniesz temat, zamienia go w źródło irytacji.']},
 'SPOŁECZNOŚĆ':{positive:['Wchodzisz w sytuację w sposób, który realnie pomaga drugiej osobie. Zyskujesz nie tylko aktywność, ale też trochę społecznego kredytu zaufania.','Twoja odpowiedź zostawia po sobie dobre wrażenie. Kilka osób zapamiętuje, że można na ciebie liczyć bez robienia z tego przedstawienia.','Reagujesz konkretnie i po ludzku. To mały moment, ale dobrze pracuje na twoją pozycję w społeczności.'],negative:['Twoja reakcja zostawia po sobie więcej niesmaku niż rozwiązania. Ludzie zaczynają oceniać nie tylko sytuację, ale też twój sposób traktowania innych.','Zamiast pomóc, dokładasz napięcie albo niepotrzebny ton. Zaufanie do ciebie dostaje mały, ale wyraźny cios.','Sposób, w jaki odpowiadasz, jest zapamiętany gorzej niż sam problem. W społeczności szybko rozchodzi się opinia, że można było załatwić to normalniej.']},
 'MODERACJA':{positive:['Trzymasz się konkretów i nie robisz publicznego spektaklu. Sprawa staje się łatwiejsza do rozwiązania, a twoja reakcja wygląda dojrzale.','Zamiast walczyć z samą obecnością zasad, próbujesz załatwić problem w uporządkowany sposób. To poprawia twoją wiarygodność.','Reagujesz bez zbędnej eskalacji wobec moderacji. Nawet jeśli sytuacja nie jest idealna, wychodzisz z niej z większym zaufaniem.'],negative:['Wchodzisz w starcie z zasadami lub moderacją bez większego planu. Problem szybko przestaje dotyczyć tylko pierwotnej sytuacji.','Twoja reakcja sprawia, że temat robi się bardziej regulaminowy niż wcześniej. Rośnie kontrowersyjność, a zaufanie do ciebie maleje.','Zamiast rozwiązać problem, dokładasz kolejny punkt zapalny między sobą a moderacją.']},
 'DYSKUSJA':{positive:['Porządkujesz argumenty i odpowiadasz na temat zamiast na osobę. Dyskusja nie staje się dzięki temu idealna, ale odzyskuje sens.','Twoja reakcja przesuwa rozmowę z emocji z powrotem na konkrety. Kilka osób zaczyna traktować twój głos jako wartościowy punkt odniesienia.','Nie dajesz się wciągnąć w tanią eskalację. Nawet różniący się z tobą użytkownicy widzą, że potrafisz dyskutować bez rozbijania rozmowy.'],negative:['Argument schodzi na drugi plan, a twoja reakcja przesuwa rozmowę w stronę personalnej przepychanki.','Zamiast bronić stanowiska, zaczynasz walczyć z ludźmi. Dyskusja traci sens, za to twoja kontrowersyjność rośnie.','Twoja odpowiedź nie kończy sporu — tworzy jego głośniejszą wersję. Coraz mniej osób pamięta, o co właściwie chodziło.']},
 'WKURW':{positive:['Nie pozwalasz, żeby chwilowa irytacja przejęła stery. Problem pozostaje irytujący, ale ty nie dokładasz do niego własnej katastrofy.','Wybierasz reakcję, która oszczędza wszystkim kolejnej awantury. Kontrolujesz frustrację zamiast publikować ją całemu serwerowi.','Irytacja jest uzasadniona, ale nie robisz z niej broni masowego rażenia. To działa na korzyść twojej reputacji.'],negative:['Frustracja przejmuje kontrolę i odpowiadasz znacznie ostrzej, niż wymagała sytuacja. Problem robi się teraz także problemem z tobą.','Wkurzenie wychodzi publicznie w najgorszej możliwej formie. Część osób rozumie powód, ale znacznie mniej osób akceptuje sposób.','Zamiast rozładować irytację, rozprowadzasz ją po całym kanale. Atmosfera siada, a twoja kontrowersyjność rośnie.']},
 'CHAOS':{positive:['W całym zamieszaniu znajdujesz prosty ruch, który przywraca trochę porządku. Ludzie szybko zauważają, że ktoś wreszcie ogarnia sytuację.','Nie próbujesz przekrzyczeć chaosu — porządkujesz go. Efekt jest mały, ale wystarczający, żeby sytuacja nie rozpadła się jeszcze bardziej.','Wybierasz rozwiązanie zamiast kolejnego żartu z problemu. Serwer na moment odzyskuje logikę.'],negative:['Chaos już był spory, ale twoja reakcja dokłada mu kolejną warstwę. Po chwili nikt nie wie, co było problemem, a co twoim wkładem.','Zamiast wyjścia awaryjnego wybierasz przycisk z napisem „jeszcze więcej chaosu”. Rezultat jest dokładnie tak przewidywalny, jak brzmi.','Dokładasz własny bałagan do sytuacji, która ledwo trzymała się w całości. Rosną aktywność i rozpoznawalność, ale niekoniecznie z dobrego powodu.']},
 'NOCNA MELINA':{positive:['Mimo późnej pory zachowujesz więcej rozsądku niż reszta kanału. Noc trwa dalej, ale bez twojego udziału w kolejnej katastrofie.','Wybierasz reakcję, która zostawia po nocnej rozmowie dobrą historię zamiast kaca reputacyjnego.','Nocny chaos nie wygrywa tym razem. Łapiesz dystans i utrzymujesz dobrą atmosferę.'],negative:['Pora robi swoje i rozsądek zostaje odłożony na jutro. Twoja reakcja podkręca nocny chaos i zostawia konsekwencje na kolejny dzień.','Dajesz się ponieść nocnej energii. Jest głośniej i aktywniej, ale rano część tej historii nie wygląda już tak zabawnie.','Zamiast wyhamować, wybierasz pełne wejście w nocny chaos. Serwer dostaje materiał do wspominania, a ty kilka nowych problemów.']},
 'EVENT':{positive:['Pomagasz sytuacji dojść do sensownego finału. Organizacja zyskuje, a twoja obecność jest kojarzona z rozwiązaniem zamiast problemem.','Włączasz się w odpowiednim momencie i realnie poprawiasz przebieg wydarzenia. To przekłada się na zaufanie i reputację.'],negative:['Twoja reakcja utrudnia coś, co już wymagało organizacji. Zamiast pomóc wydarzeniu, stajesz się jego dodatkowym problemem.','Wchodzisz w konflikt z przebiegiem wydarzenia i robisz wokół siebie więcej zamieszania niż pożytku.']},
 'EKIPA':{positive:['Reagujesz tak, że wspólna relacja wychodzi z sytuacji mocniejsza, a nie bardziej napięta.','Nie robisz z drobnego problemu testu lojalności. Ekipa odbiera to jako dobry sygnał.'],negative:['Mały problem zamienia się w osobistą przepychankę. Relacje z ekipą dostają niepotrzebny rykoszet.','Sposób reakcji sprawia, że nawet znajomi zaczynają trzymać większy dystans.']},
 'KULTURA':{positive:['Dokładasz coś, co dobrze wpisuje się w lokalne lore zamiast je na siłę eksploatować.','Twoja reakcja wzmacnia serwerowy folklor i daje ludziom kolejny wspólny punkt odniesienia.'],negative:['Próbujesz za mocno sterować żartem lub lore i zaczynasz psuć coś, co działało naturalnie.','Zamiast podtrzymać serwerowy klimat, przeciągasz temat do momentu, w którym część osób ma go dość.']},
 'POZYCJA':{positive:['Wykorzystujesz rosnącą pozycję bez robienia z niej demonstracji ego. To wzmacnia twój autorytet.','Dostajesz więcej uwagi i odpowiadasz na nią odpowiedzialnie. Twoja pozycja staje się bardziej stabilna.'],negative:['Rosnąca pozycja uderza trochę za mocno do głowy. Ludzie szybko wyłapują ton wyższości.','Zamiast wykorzystać status jako przewagę społeczną, zamieniasz go w powód do dystansu i irytacji.']}
};
function narrativeBase(ev,c){const type=c.outcome==='negative'?'negative':'positive',cat=String(ev.category||'').toUpperCase(),set=NARRATIVES[cat]||NARRATIVES['SPOŁECZNOŚĆ'],arr=set[type]||[];return arr[hash32(`${ev.id}|${c.label}|${type}`)%Math.max(1,arr.length)]||''}
function decisionNarrative(ev,c,scoreDelta){const type=c.outcome==='negative'?'negative':'positive',specific=cleanResultText(c.result||''),base=specific||narrativeBase(ev,c);let point;if(type==='positive'&&scoreDelta>=0)point=`Punktowo decyzja również się broni: +${scoreDelta} PKT.`;else if(type==='positive')point=`Sama reakcja była rozsądna, ale tym razem losowanie punktowe obraca się przeciwko tobie: ${scoreDelta} PKT.`;else if(scoreDelta>=0)point=`Ryzykowna reakcja mimo wszystko daje krótkoterminowy punktowy zysk: +${scoreDelta} PKT.`;else point=`Konsekwencje są odczuwalne także punktowo: ${scoreDelta} PKT.`;return`${base}${base&&/[.!?]$/.test(base)?'':' .'} ${point}`.replace(' .','.').trim()}

function render(){const has=!!state;$('startScreen').classList.toggle('hidden',has);$('gameScreen').classList.toggle('hidden',!has);if(!has)return;normalizeState(state);$('profileNick').textContent=state.nickname;$('profileRole').textContent=state.role;$('levelValue').textContent=state.level;$('tenureValue').textContent=`${state.turn-1} tyg.`;$('scoreValue').textContent=state.score;$('statusValue').textContent=state.status;$('moneyValue').textContent=state.melons;$('streakValue').textContent=state.streak||0;$('turnTitle').textContent=`TYDZIEŃ ${state.turn}`;$('calendarYearValue').textContent=year();$('turnSubtitle').textContent=`Rok ${year()} • tydzień ${week()}/52`;$('eventsCount').textContent=state.eventCount;$('goodChoices').textContent=state.goodChoices;$('badChoices').textContent=state.badChoices;$('autoEventsCount').textContent=state.autoEventCount;$('bestLevel').textContent=state.bestLevel;const xp=xpProgress(state.score);$('levelProgressFill').style.width=`${xp.percent}%`;$('levelProgressText').textContent=state.level>=Number(leveling().maxLevel||50)?'MAKSYMALNY POZIOM':`${xp.inside} / ${xp.need} XP do poziomu ${state.level+1}`;renderBars();renderHistory();renderMilestones();renderGalaCard();$('nextEventBtn').disabled=!!state.ended;if(state.ended)showEnding(state.ending,false);else scheduleGala()}
function renderBars(){$('statsBars').innerHTML=defs.map(([k,l,c])=>`<div class="${c}"><div class="barhead"><span>${l}</span><b>${Math.round(state[k])}</b></div><div class="bar"><div style="width:${state[k]}%"></div></div></div>`).join('')}
function renderHistory(){$('historyList').innerHTML=state.history.length?state.history.slice(0,100).map(h=>`<div class="entry ${h.outcome||''}"><div class="when">TYDZ. ${h.turn}</div><div><strong>${esc(h.title)}</strong><div class="detail">${esc(h.detail||'')}</div></div><div class="delta ${h.outcome||''}">${esc(h.delta||'')}</div></div>`).join(''):'<div class="hint">Jeszcze nic się nie wydarzyło.</div>'}
function renderMilestones(){const m=[['Pierwszy event',s=>s.eventCount>=1],['Stały bywalec',s=>s.level>=3],['Rozpoznawalność 60+',s=>s.popularity>=60],['Zaufanie 75+',s=>s.trust>=75],['Pół roku',s=>s.turn>=27],['Rok',s=>s.turn>=53],['Kandydat na moderatora',s=>s.level>=8&&s.trust>=70&&s.reputation>=65]];$('milestonesList').innerHTML=m.map(([l,f])=>`<div class="mile ${f(state)?'done':''}"><span class="dot"></span>${l}</div>`).join('')}
function weighted(a){let total=0;const w=a.map(e=>{const x=Math.max(1,Number(e.weight)||1)*rnd(.4,1.65);total+=x;return x});let r=rng()*total;for(let i=0;i<a.length;i++){r-=w[i];if(r<=0)return a[i]}return a.at(-1)}
function eventPool(){const a=events.filter(e=>e.enabled&&state.turn>=e.minTurn&&!completedOneTime(e)),recent=new Set(state.history.slice(0,15).map(h=>h.eventId)),b=a.filter(e=>!recent.has(e.id));return b.length?b:a}
function autoPool(){const a=autoEvents.filter(e=>e.enabled&&state.turn>=e.minTurn&&!completedOneTime(e)),recent=new Set(state.history.slice(0,12).map(h=>h.eventId)),b=a.filter(e=>!recent.has(e.id));return b.length?b:a}
function draw(){if(!ready)return toast('Baza nie jest gotowa.');if(state.ended)return toast('Kariera jest zakończona.');if(current)return toast('Najpierw zakończ aktualny event.');$('eventCard')?.classList.remove('auto-event');const ap=autoPool();if(ap.length&&rng()<clamp(Number(meta.automaticEventChance??.28),0,1))return runAuto(weighted(ap));const p=eventPool();if(!p.length)return toast('Brak dostępnych eventów.');current=normEvent(weighted(p));current.displayChoices=shuffle(current.choices);$('eventCategory').textContent=current.category+(current.oneTime?' • JEDNORAZOWY':'');$('eventTitle').textContent=current.title;$('eventDescription').textContent=current.description;$('eventResult').classList.add('hidden');$('choiceGrid').style.gridTemplateColumns='repeat(2,minmax(0,1fr))';$('choiceGrid').innerHTML=current.displayChoices.map((c,i)=>{const type=c.outcome==='negative'?'DECYZJA RYZYKOWNA':'DECYZJA ROZSĄDNA';return`<button class="choice" data-choice="${i}"><strong>${esc(c.label)}</strong><span>${type}<br>${esc(chanceLabel(c.pointChances))}</span></button>`}).join('');document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>resolveChoice(+b.dataset.choice));$('nextEventBtn').disabled=true}
function resolveChoice(i){const c=current?.displayChoices?.[i];if(!c)return;const ev=current,decisionType=c.outcome==='negative'?'negative':'positive',statEffects=apply(c.effects),pointRoll=rollPointOutcome(c.pointChances),scoreDelta=applyExactScore(pointRoll.points),allEffects={...statEffects,score:scoreDelta},narrative=decisionNarrative(ev,c,scoreDelta);state.eventCount++;if(decisionType==='positive'){state.goodChoices++;state.streak=(state.streak||0)+1}else{state.badChoices++;state.streak=0}markOneTime(ev);state.history.unshift({turn:state.turn,eventId:ev.id,category:ev.category,title:ev.title,detail:narrative,delta:summary(allEffects),outcome:decisionType});$('choiceGrid').innerHTML='';$('eventResult').textContent=`REAKCJA: ${decisionType==='positive'?'POZYTYWNA':'NEGATYWNA'}${ev.oneTime?' • EVENT JEDNORAZOWY':''}\n\n${narrative}\n\nSZANSE PUNKTOWE: ${chanceLabel(c.pointChances)}\nWYNIK LOSOWANIA: ${pointRoll.chance}% → ${scoreDelta>0?'+':''}${scoreDelta} PKT\nZMIANY: ${summary(allEffects)}`;$('eventResult').classList.remove('hidden');state.turn++;current=null;finishWeek()}
function runAuto(ev){ev=normAuto(ev);$('eventCard')?.classList.add('auto-event');$('eventCategory').innerHTML=`${esc(ev.category)} <span class="auto-event-badge">BEZ DECYZJI${ev.oneTime?' • JEDNORAZOWY':''}</span>`;$('eventTitle').textContent=ev.title;$('eventDescription').textContent=ev.description;$('choiceGrid').innerHTML='';const out=apply(ev.effects);if(Number(ev.effects?.score))out.score=applyExactScore(ev.effects.score);$('eventResult').textContent=`ZDARZENIE AUTOMATYCZNE — bez możliwości podjęcia decyzji.\n\n${ev.result}\n\nZMIANY: ${summary(out)}`;$('eventResult').classList.remove('hidden');state.eventCount++;state.autoEventCount++;markOneTime(ev);state.history.unshift({turn:state.turn,eventId:ev.id,category:ev.category,title:ev.title,detail:ev.result,delta:summary(out),outcome:'automatic'});state.turn++;current=null;finishWeek()}
function finishWeek(){const ending=checkEnding();save();render();$('nextEventBtn').textContent=ending?'KARIERA ZAKOŃCZONA':'NASTĘPNY EVENT';if(ending)showEnding(ending)}
function checkEnding(){if(state.ended)return state.ending;if(state.reputation<=3||state.trust<=3||state.controversy>=98){state.ended=true;state.ending='ban';return'ban'}if(state.level>=10&&state.trust>=80&&state.reputation>=75&&state.controversy<=35&&state.turn>=26){state.ended=true;state.ending='moderator';return'moderator'}return null}
function showEnding(type,doSave=true){if(!type)return;$('endingIcon').textContent=type==='moderator'?'🛡️':'🔨';$('endingTitle').textContent=type==='moderator'?'ZOSTAJESZ MODERATOREM!':'DOSTAJESZ BANA!';$('endingText').textContent=type==='moderator'?'Po długiej karierze i zdobyciu wysokiego poziomu doświadczenia otrzymujesz rolę moderatora.':'Przekraczasz granicę — kariera kończy się banem.';$('endingModal').classList.remove('hidden');if(doSave)save()}

function runGala(){if(!state||state.ended||week()!==52||state.galas?.[year()])return false;const y=year();state.galas[y]={year:y,week:state.turn,nominees:[],winner:'',results:[],schema:714,pendingCategoryResults:true};state.history.unshift({turn:state.turn,eventId:`golden_melons_${y}`,category:'ZŁOTE MELONY',title:`Złote Melony ${y}`,detail:'Rozpoczyna się coroczna gala. Wyniki wszystkich kategorii są liczone w panelu Złotych Melonów.',delta:'GALA',outcome:'automatic'});save();renderGalaCard();renderGalaModal(y);modal('goldenMelonsModal',true);toast(`Złote Melony ${y}: rozpoczynamy galę!`);return true}
function scheduleGala(){if(galaOpening||!state||state.ended||week()!==52||state.galas?.[year()])return;galaOpening=true;setTimeout(()=>{try{runGala()}finally{galaOpening=false}},0)}
function renderGalaCard(){if(!state)return;const y=year(),g=state.galas?.[y];$('goldenMelonsYear').textContent=y;$('goldenMelonsStatus').textContent=g?(g.winner?`Gala ${y} zakończona. Użytkownik Roku: ${g.winner}.`:`Gala ${y} rozpoczęta — sprawdź pełne wyniki w panelu.`):`Gala uruchomi się automatycznie w 52. tygodniu. Baza: ${serverUsers.length} użytkowników.`;$('goldenMelonsBtn').textContent=g?`ZOBACZ WYNIKI ${y}`:`PODGLĄD GALI ${y}`}
function renderGalaModal(y=year()){$('galaModalYear').textContent=y;$('galaUsersList').innerHTML=serverUsers.length?serverUsers.map(n=>`<div class="gala-user"><span>${esc(n)}</span></div>`).join(''):'<div class="hint">Brak użytkowników. Uzupełnij data/users.txt.</div>';if(!state?.galas?.[y])$('galaResults').innerHTML='<div class="hint">W 52. tygodniu system uruchomi pełną galę Złotych Melonów.</div>'}
function openGala(){renderGalaModal(year());modal('goldenMelonsModal',true)}
function modal(id,on=true){$(id)?.classList.toggle('hidden',!on)}
function download(data,name){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function readJson(f){return JSON.parse(await f.text())}

function replaceState(next,{doRender=true,doSave=true}={}){if(!next||typeof next!=='object')return null;state=normalizeState(next);syncOneTimeFromHistory();current=null;if(doSave)save();if(doRender)render();return state}
function getState(){return state?JSON.parse(JSON.stringify(state)):null}
globalThis.MelonCoreV714={getState,replaceState,levelForScore,xpRequiredForLevel,xpCostForLevel,xpProgress,render:()=>render(),save:()=>save(),version:'7.14'};

function bind(){
  $('startBtn').onclick=()=>{if(!ready)return toast('Najpierw musi załadować się baza.');state=fresh();current=null;save();render();toast('Kariera rozpoczęta od poziomu 1.')};
  $('nextEventBtn').onclick=draw;$('optionsBtn').onclick=()=>modal('optionsModal');$('goldenMelonsBtn').onclick=openGala;$('saveBtn').onclick=()=>{save();toast('Zapisano.')};
  $('newCareerBtn').onclick=()=>{if(confirm('Rozpocząć nową karierę?')){state=null;current=null;localStorage.removeItem(AUTO);modal('endingModal',false);render()}};
  $('clearHistoryBtn').onclick=()=>{if(state&&confirm('Wyczyścić historię? Jednorazowe eventy pozostaną oznaczone jako rozegrane.')){state.history=[];save();render()}};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>modal(b.dataset.close,false));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m&&m.id!=='endingModal')modal(m.id,false)});
  $('endingNewCareerBtn').onclick=()=>{state=null;current=null;localStorage.removeItem(AUTO);modal('endingModal',false);render()};
  $('exportSaveBtn').onclick=()=>state&&download(state,`melonawka-${state.nickname}.json`);
  $('importSaveInput').onchange=async e=>{try{replaceState(await readJson(e.target.files[0]));toast('Wczytano zapis.')}catch(x){alert(x.message)}e.target.value=''};
  document.querySelectorAll('[data-save-slot]').forEach(b=>b.onclick=()=>{if(state){localStorage.setItem(SLOT+b.dataset.saveSlot,JSON.stringify(state));toast('Slot zapisany.')}});
  document.querySelectorAll('[data-load-slot]').forEach(b=>b.onclick=()=>{const x=load(SLOT+b.dataset.loadSlot);if(x){replaceState(x);toast('Slot wczytany.')}else toast('Slot pusty.')});
  window.addEventListener('beforeunload',save)
}
async function init(){bind();dbStatus();await loadDatabase();if(state)replaceState(state,{doSave:false,doRender:false});render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js?v=7.14.0').catch(()=>{})}
init();
})();
