(()=>{'use strict';
const AUTO='melon_auto_v5',WALLET='melon_wallet_v74',WEEKS=52,START_YEAR=2026;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const SHOP=[
  {id:'rep',icon:'⭐',name:'Pakiet reputacji',cost:45,desc:'+6 reputacji',apply:s=>s.reputation=clamp(Number(s.reputation||0)+6,0,100)},
  {id:'trust',icon:'🤝',name:'Akcja integracyjna',cost:50,desc:'+6 zaufania',apply:s=>s.trust=clamp(Number(s.trust||0)+6,0,100)},
  {id:'activity',icon:'⚡',name:'Pakiet aktywności',cost:35,desc:'+8 aktywności',apply:s=>s.activity=clamp(Number(s.activity||0)+8,0,100)},
  {id:'drama',icon:'🛡️',name:'Tarcza antydrama',cost:55,desc:'-10 kontrowersyjności',apply:s=>s.controversy=clamp(Number(s.controversy||0)-10,0,100)},
  {id:'xp',icon:'📈',name:'Mentoring kariery',cost:75,desc:'+75 punktów / XP',apply:s=>{s.score=Math.max(0,Number(s.score||0)+75);s.level=Math.max(1,Math.floor(s.score/250)+1);s.bestLevel=Math.max(Number(s.bestLevel||1),s.level)}}
];
function getState(){try{return JSON.parse(localStorage.getItem(AUTO))}catch{return null}}
function saveState(s){localStorage.setItem(AUTO,JSON.stringify(s));localStorage.setItem(WALLET,String(Math.max(0,Number(s.melons||0))))}
function year(s){return START_YEAR+Math.floor((Math.max(1,Number(s?.turn||1))-1)/WEEKS)}
function week(s){return((Math.max(1,Number(s?.turn||1))-1)%WEEKS)+1}
function wallet(s=getState()){return Math.max(0,Number(s?.melons??localStorage.getItem(WALLET)??0))}
function toast(t){let e=$('#navToast');if(!e){e=document.createElement('div');e.id='navToast';e.className='nav-toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function ensureHub(){let h=$('#careerHub');if(h)return h;h=document.createElement('div');h.id='careerHub';h.className='career-hub hidden';h.innerHTML='<div class="career-hub-backdrop" data-hub-close></div><section class="career-hub-window"><header class="career-hub-head"><div><div class="eyebrow" id="hubEyebrow">MELONAWKA</div><h2 id="hubTitle">Centrum kariery</h2></div><button class="hub-close" type="button" data-hub-close>×</button></header><div id="hubBody" class="career-hub-body"></div></section>';document.body.appendChild(h);h.addEventListener('click',e=>{if(e.target.closest('[data-hub-close]'))closeHub()});return h}
function closeHub(){ensureHub().classList.add('hidden');markActive('home')}
function openHub(title,eyebrow,html){const h=ensureHub();$('#hubTitle').textContent=title;$('#hubEyebrow').textContent=eyebrow;$('#hubBody').innerHTML=html;h.classList.remove('hidden')}
function noCareer(){return '<div class="hub-empty"><div class="hub-empty-icon">🍉</div><h3>Najpierw rozpocznij karierę</h3><p>Ta sekcja korzysta z danych aktualnego użytkownika.</p><button class="btn primary" data-nav="home">WRÓĆ DO SYMULATORA</button></div>'}
function careerView(){const s=getState();if(!s)return openHub('Centrum kariery','KARIERA',noCareer());const mod=[['Poziom 10+',s.level>=10,`LVL ${s.level}`],['Reputacja 75+',s.reputation>=75,Math.round(s.reputation)],['Zaufanie 80+',s.trust>=80,Math.round(s.trust)],['Kontrowersyjność ≤35',s.controversy<=35,Math.round(s.controversy)],['StaŜ 26+ tyg.',s.turn>=26,`${s.turn-1} tyg.`]];openHub('Centrum kariery','KARIERA',`<div class="hub-hero"><div class="hub-avatar">🍉</div><div><h3>${esc(s.nickname)}</h3><p>${esc(s.role||'NOWICJUSZ')} • Rok ${year(s)}, tydzień ${week(s)}/52</p></div><div class="hub-wallet">${wallet(s)} 🍉</div></div><div class="hub-cards"><div class="hub-card"><span>Poziom</span><b>${s.level}</b></div><div class="hub-card"><span>Punkty</span><b>${s.score}</b></div><div class="hub-card"><span>Najwyższy LVL</span><b>${s.bestLevel||s.level}</b></div><div class="hub-card"><span>Eventy</span><b>${s.eventCount||0}</b></div></div><h3 class="hub-section-title">Droga do moderatora</h3><div class="career-checks">${mod.map(([n,ok,v])=>`<div class="career-check ${ok?'done':''}"><span>${ok?'✓':'○'}</span><strong>${n}</strong><b>${v}</b></div>`).join('')}</div><h3 class="hub-section-title">Stan profilu</h3><div class="career-stat-list">${[['Reputacja',s.reputation],['Aktywność',s.activity],['Rozpoznawalność',s.popularity],['Kontrowersyjność',s.controversy],['Zaufanie',s.trust]].map(([n,v])=>`<div><span>${n}</span><div class="mini-progress"><i style="width:${clamp(Number(v||0),0,100)}%"></i></div><b>${Math.round(v||0)}</b></div>`).join('')}</div>`)}
function shopView(){const s=getState();if(!s)return openHub('Melonowy Skarbiec','SKLEP',noCareer());const w=wallet(s);openHub('Melonowy Skarbiec','SKLEP • ROZWÓJ KARIERY',`<div class="shop-wallet"><div><span>Twoje saldo</span><strong>${w} 🍉</strong></div><p>Melony możesz wydawać na natychmiastowy rozwój profilu. Zakup zapisuje się w karierze.</p></div><div class="shop-grid">${SHOP.map(x=>`<article class="shop-item"><div class="shop-icon">${x.icon}</div><div class="shop-info"><h3>${x.name}</h3><p>${x.desc}</p></div><button class="shop-buy" data-shop="${x.id}" ${w<x.cost?'disabled':''}><span>${x.cost} 🍉</span><b>${w<x.cost?'ZA MAŁO':'KUP'}</b></button></article>`).join('')}</div><div class="hub-note">Melon Boost przed decyzją nadal działa niezależnie od tego sklepu.</div>`);$$('[data-shop]').forEach(b=>b.onclick=()=>buy(b.dataset.shop))}
function buy(id){const item=SHOP.find(x=>x.id===id),s=getState();if(!item||!s)return;const w=wallet(s);if(w<item.cost)return toast('Masz za mało Melonów.');s.melons=w-item.cost;item.apply(s);saveState(s);toast(`${item.name}: zakupiono za ${item.cost} Melonów.`);setTimeout(()=>location.reload(),550)}
function eventsView(){const s=getState();if(!s)return openHub('Eventy','EVENTY',noCareer());const hist=Array.isArray(s.history)?s.history:[],cats={};for(const h of hist)cats[h.category||'INNE']=(cats[h.category||'INNE']||0)+1;const top=Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,6);openHub('Centrum eventów','EVENTY',`<div class="hub-cards"><div class="hub-card"><span>Wszystkie</span><b>${s.eventCount||0}</b></div><div class="hub-card"><span>Losowe</span><b>${s.autoEventCount||0}</b></div><div class="hub-card good"><span>Dobre decyzje</span><b>${s.goodChoices||0}</b></div><div class="hub-card bad"><span>Złe decyzje</span><b>${s.badChoices||0}</b></div></div><h3 class="hub-section-title">Najczęstsze kategorie</h3><div class="category-list">${top.length?top.map(([n,v])=>`<div><span># ${esc(n)}</span><b>${v}</b></div>`).join(''):'<p class="hint">Brak rozegranych eventów.</p>'}</div><h3 class="hub-section-title">Ostatnie zdarzenia</h3>${historyRows(hist.slice(0,8))}`)}
function statsView(){const s=getState();if(!s)return openHub('Statystyki','STATYSTYKI',noCareer());const good=Number(s.goodChoices||0),bad=Number(s.badChoices||0),dec=good+bad,rate=dec?Math.round(good/dec*100):0;const gala=Object.values(s.galas||{});openHub('Statystyki kariery','STATYSTYKI',`<div class="stats-big"><div><span>Skuteczność decyzji</span><strong>${rate}%</strong><small>${good} dobrych / ${bad} złych</small></div><div><span>StaŜ</span><strong>${s.turn-1}</strong><small>tygodni</small></div><div><span>Melony</span><strong>${wallet(s)}</strong><small>aktualne saldo</small></div><div><span>Gale</span><strong>${gala.length}</strong><small>Złote Melony</small></div></div><h3 class="hub-section-title">Parametry</h3><div class="career-stat-list">${[['Reputacja',s.reputation],['Aktywność',s.activity],['Rozpoznawalność',s.popularity],['Kontrowersyjność',s.controversy],['Zaufanie',s.trust]].map(([n,v])=>`<div><span>${n}</span><div class="mini-progress"><i style="width:${clamp(Number(v||0),0,100)}%"></i></div><b>${Math.round(v||0)}</b></div>`).join('')}</div>`)}
function historyRows(hist){return hist.length?`<div class="hub-history">${hist.map(h=>`<div class="hub-history-row"><span class="hub-week">T${h.turn}</span><div><strong>${esc(h.title)}</strong><p>${esc(h.detail||'')}</p></div><b class="${h.outcome||''}">${esc(h.delta||'')}</b></div>`).join('')}</div>`:'<div class="hint">Historia jest jeszcze pusta.</div>'}
function historyView(){const s=getState();if(!s)return openHub('Historia serwera','HISTORIA',noCareer());openHub('Historia serwera','HISTORIA KARIERY',`<div class="history-summary">Zapisano <b>${(s.history||[]).length}</b> wpisów w tej karierze.</div>${historyRows((s.history||[]).slice(0,50))}`)}
function openGolden(){closeHub();const s=getState();if(!s)return toast('Najpierw rozpocznij karierę.');const b=$('#goldenMelonsBtn');if(b)b.click();else toast('Panel Złotych Melonów jest chwilowo niedostępny.')}
function home(){ensureHub().classList.add('hidden');markActive('home');const target=$('#gameScreen:not(.hidden)')||$('#startScreen');target?.scrollIntoView({behavior:'smooth',block:'start'})}
const ROUTES={home,career:careerView,shop:shopView,events:eventsView,stats:statsView,golden:openGolden,history:historyView};
function markActive(route){$$('.channel[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===route||route==='home'&&x.dataset.nav==='home'));$$('.server-icon[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===route||route==='home'&&x.dataset.nav==='home'))}
function go(route){(ROUTES[route]||home)();if(route!=='golden')markActive(route)}
function makeClickable(el,route){if(!el)return;el.dataset.nav=route;el.setAttribute('role','button');el.tabIndex=0;el.classList.add('nav-clickable');el.addEventListener('click',()=>go(route));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go(route)}})}
function setupNav(){const icons={Melonawka:'home','Społeczność':'career','Eventy':'events','Złote Melony':'golden','Statystyki':'stats'};$$('.server-icon').forEach(x=>makeClickable(x,icons[x.title]||'home'));const channels={'melonawka-simulator':'home','kariera':'career','melonowy-skarbiec':'shop','eventy':'events','statystyki':'stats','złote-melony':'golden','historia-serwera':'history'};$$('.channel').forEach(x=>makeClickable(x,channels[x.textContent.trim()]||'home'));const v=$('.mini-user span');if(v)v.textContent='● online • V7.5';document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n&&n.closest('#careerHub'))go(n.dataset.nav)});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!ensureHub().classList.contains('hidden'))closeHub()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupNav);else setupNav();
})();