(()=>{'use strict';
const AUTO='melon_auto_v5',MANIFEST='./data/database.json',REL_PREFIX='melon_relations_v710_',ACTION_PREFIX='melon_relation_actions_v714_';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=s=>String(s||'').trim().toLocaleLowerCase('pl');
let users=[],cfg={activeInteractionsPerWeek:3,cooldownSameUserWeeks:1,relationMemoryLimit:40},filter='all',query='',selected='',busy=false,lastRender='';
const SKILLS={communication:{name:'Komunikacja',icon:'💬'},empathy:{name:'Empatia',icon:'🫶'},teamwork:{name:'Współpraca',icon:'🤝'},humor:{name:'Humor',icon:'😂'},assertiveness:{name:'Asertywność',icon:'🧭'}};
const ACTIONS={
 voice:{icon:'🎙️',name:'Pogadaj na voice',desc:'Luźna rozmowa. Dobra do budowania więzi i komunikacji.',base:73,skills:['communication','empathy'],success:{rel:{score:6,bond:4,respect:2,chemistry:2,tension:-2},career:{trust:3,activity:3,score:22},skills:{communication:2,empathy:1}},fail:{rel:{score:-3,bond:-1,tension:4},career:{trust:-2,controversy:2,score:-6},skills:{communication:-1}}},
 game:{icon:'🎮',name:'Zagrajcie razem',desc:'Wspólna gra może zbliżyć albo bardzo szybko popsuć atmosferę.',base:67,skills:['teamwork','communication'],success:{rel:{score:7,bond:5,respect:2,chemistry:4,tension:-1},career:{activity:5,popularity:2,trust:2,score:26},skills:{teamwork:2,communication:1}},fail:{rel:{score:-5,bond:-2,respect:-1,tension:6},career:{trust:-3,controversy:4,score:-12},skills:{teamwork:-1}}},
 project:{icon:'🛠️',name:'Wspólny projekt',desc:'Duży potencjał rozwoju, ale też spore ryzyko tarć przy współpracy.',base:59,skills:['teamwork','communication'],success:{rel:{score:10,bond:5,respect:7,chemistry:2,tension:-2},career:{reputation:6,trust:5,activity:6,score:45},skills:{teamwork:3,communication:2}},fail:{rel:{score:-7,bond:-3,respect:-3,tension:8},career:{activity:-3,trust:-4,controversy:5,score:-18},skills:{teamwork:-2,communication:-1}}},
 dm:{icon:'📨',name:'Pogadaj prywatnie',desc:'Rozmowa jeden na jeden rozwija zaufanie i empatię.',base:74,skills:['empathy','communication'],success:{rel:{score:7,bond:5,respect:2,tension:-4},career:{trust:5,reputation:2,score:20},skills:{empathy:2,communication:1}},fail:{rel:{score:-4,bond:-2,tension:4},career:{trust:-3,score:-8},skills:{communication:-1}}},
 meme:{icon:'😂',name:'Podeślij mema',desc:'Sprawdź, czy macie podobne poczucie humoru.',base:68,skills:['humor'],chemistry:.10,success:{rel:{score:6,bond:2,chemistry:7,tension:-1},career:{popularity:6,activity:3,score:24},skills:{humor:2}},fail:{rel:{score:-3,chemistry:-4,tension:3},career:{popularity:-2,controversy:3,score:-6},skills:{humor:-1}}},
 support:{icon:'🫂',name:'Pomóż w problemie',desc:'Poświęć czas na pomoc. Dobrze buduje szacunek i więź.',base:69,skills:['empathy','teamwork'],success:{rel:{score:8,bond:5,respect:6,tension:-3},career:{trust:6,reputation:5,activity:2,score:32},skills:{empathy:2,teamwork:1}},fail:{rel:{score:-2,respect:-1,tension:2},career:{activity:-2,score:-5},skills:{empathy:-1}}},
 askhelp:{icon:'🙋',name:'Poproś o pomoc',desc:'Oddaj część kontroli drugiej osobie i sprawdź, czy możesz na niej polegać.',base:65,skills:['communication'],requires:e=>e.bond>=18||e.score>=10,locked:'Potrzebujesz przynajmniej relacji „Znajomy” albo więzi 18+.',success:{rel:{score:6,bond:5,respect:1,tension:-2},career:{trust:4,score:18},skills:{communication:1}},fail:{rel:{score:-2,bond:-1,tension:3},career:{trust:-1,score:-4},skills:{communication:-1}}},
 reconcile:{icon:'🕊️',name:'Spróbuj się pogodzić',desc:'Specjalna akcja dla napiętych lub chłodnych relacji.',base:57,skills:['empathy','communication'],requires:e=>e.tension>=35||e.score<0,locked:'Ta akcja pojawia się przy napięciu 35+ albo relacji poniżej zera.',tension:-.12,success:{rel:{score:12,bond:4,respect:4,tension:-16},career:{trust:6,reputation:3,controversy:-3,score:28},skills:{empathy:3,communication:2}},fail:{rel:{score:-8,bond:-2,respect:-2,tension:10},career:{trust:-5,controversy:5,score:-15},skills:{empathy:-1,communication:-1}}},
 debate:{icon:'⚔️',name:'Wejdź w ostrą dyskusję',desc:'Ryzykowne starcie. Może zbudować szacunek albo nową rywalizację.',base:52,skills:['assertiveness','communication'],tension:-.08,success:{rel:{score:4,respect:6,chemistry:1,tension:1},career:{reputation:5,activity:4,score:32},skills:{assertiveness:2,communication:1}},fail:{rel:{score:-9,bond:-2,respect:-5,tension:10},career:{controversy:8,trust:-5,reputation:-3,score:-20},skills:{assertiveness:-1,communication:-1}}},
 prank:{icon:'🎭',name:'Zrób mały prank',desc:'Wysokie ryzyko. Działa najlepiej przy dobrej chemii i niskim napięciu.',base:54,skills:['humor','empathy'],chemistry:.12,tension:-.10,requires:e=>e.chemistry>=30,locked:'Potrzebujesz chemii 30+.',success:{rel:{score:8,bond:3,chemistry:8,tension:-1},career:{popularity:5,activity:3,score:28},skills:{humor:3}},fail:{rel:{score:-10,bond:-4,respect:-3,chemistry:-5,tension:11},career:{trust:-5,controversy:7,score:-18},skills:{humor:-1,empathy:-1}}}
};
function json(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function state(){return globalThis.MelonCoreV714?.getState?.()||json(AUTO)}
function syncState(s){if(globalThis.MelonCoreV714?.replaceState)globalThis.MelonCoreV714.replaceState(s);else localStorage.setItem(AUTO,JSON.stringify(s))}
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h>>>0}
function rand(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}catch{return Math.random()}}
function careerId(s){return String(s?.startProfileV79?.rolledAt||`${s?.nickname||'user'}|${s?.difficulty||'normal'}|${s?.startYear||2026}`)}
function relKey(s){return REL_PREFIX+hash32(careerId(s)).toString(36)}
function usageKey(s){return ACTION_PREFIX+hash32(careerId(s)).toString(36)}
function parseUsers(text){const seen=new Set(),out=[];for(const raw of String(text).split(/\r?\n/)){const n=raw.trim(),k=key(n);if(!n||n.startsWith('#')||n.startsWith('//')||seen.has(k))continue;seen.add(k);out.push(n)}return out}
function skillDefaults(arch){const b={communication:45,empathy:45,teamwork:45,humor:45,assertiveness:45};if(arch==='lurker')Object.assign(b,{communication:39,empathy:53,assertiveness:39});if(arch==='regular')Object.assign(b,{communication:50,teamwork:50});if(arch==='memer')Object.assign(b,{humor:62,communication:49});if(arch==='debater')Object.assign(b,{communication:53,assertiveness:62,empathy:40});if(arch==='helper')Object.assign(b,{empathy:63,teamwork:55,communication:52});return b}
function ensureSkills(s){let changed=false;if(!s.socialSkills||typeof s.socialSkills!=='object'){s.socialSkills=skillDefaults(s.archetype);changed=true}for(const k of Object.keys(SKILLS)){const v=Number(s.socialSkills[k]);if(!Number.isFinite(v)){s.socialSkills[k]=skillDefaults(s.archetype)[k];changed=true}else{s.socialSkills[k]=clamp(Math.round(v),0,100)}}return changed}
function initialEntry(s,name){const seed=hash32(`${careerId(s)}|${name}|v715`),score=(seed%25)-12;return{score,interactions:0,manualInteractions:0,trend:0,lastTurn:0,bond:clamp(38+Math.round(score*.45)+((seed>>>5)%15),0,100),respect:clamp(42+Math.round(score*.35)+((seed>>>10)%15),0,100),chemistry:clamp(38+Math.round(score*.3)+((seed>>>15)%22),0,100),tension:clamp(24-Math.round(score*.3)+((seed>>>20)%18),0,100),actionCounts:{},memories:[]}}
function ensureEntry(s,name,e){const base=initialEntry(s,name),x=e&&typeof e==='object'?e:{};for(const k of['score','interactions','manualInteractions','trend','lastTurn','bond','respect','chemistry','tension'])if(!Number.isFinite(Number(x[k])))x[k]=base[k];x.score=clamp(Math.round(Number(x.score||0)),-100,100);for(const k of['bond','respect','chemistry','tension'])x[k]=clamp(Math.round(Number(x[k]||0)),0,100);x.interactions=Math.max(0,Math.round(Number(x.interactions||0)));x.manualInteractions=Math.max(0,Math.round(Number(x.manualInteractions||0)));x.actionCounts=x.actionCounts&&typeof x.actionCounts==='object'?x.actionCounts:{};x.memories=Array.isArray(x.memories)?x.memories:[];return x}
function relationData(s){const k=relKey(s),d=json(k,{careerId:careerId(s),users:{},processed:[],v715Processed:[]});d.users=d.users&&typeof d.users==='object'?d.users:{};d.processed=Array.isArray(d.processed)?d.processed:[];d.v715Processed=Array.isArray(d.v715Processed)?d.v715Processed:[];for(const name of users){if(key(name)===key(s.nickname))continue;d.users[name]=ensureEntry(s,name,d.users[name])}localStorage.setItem(k,JSON.stringify(d));return d}
function saveRelations(s,d){localStorage.setItem(relKey(s),JSON.stringify(d))}
function usage(s){const d=json(usageKey(s),{turn:Number(s.turn||1),used:0,lastByUser:{},log:[]});if(Number(d.turn)!==Number(s.turn||1)){d.turn=Number(s.turn||1);d.used=0}d.lastByUser=d.lastByUser||{};d.log=Array.isArray(d.log)?d.log:[];return d}
function saveUsage(s,d){localStorage.setItem(usageKey(s),JSON.stringify(d))}
function relLabel(v){if(v>=70)return['Bliski przyjaciel','best'];if(v>=45)return['Przyjaciel','friend'];if(v>=20)return['Dobry kontakt','good'];if(v>=5)return['Znajomy','warm'];if(v>-15)return['Neutralnie','neutral'];if(v>-40)return['Chłodno','cold'];if(v>-70)return['Rywal','rival'];return['Wróg','enemy']}
function skillAvg(s,names){const a=names.map(k=>Number(s.socialSkills?.[k]||45));return a.reduce((x,v)=>x+v,0)/Math.max(1,a.length)}
function chanceFor(a,s,e){const diff=s.difficulty==='hard'?-7:s.difficulty==='easy'?5:0,skill=(skillAvg(s,a.skills||[])-50)*.27,relation=Number(e.score||0)*.10,bond=(Number(e.bond||50)-50)*.045,respect=(Number(e.respect||50)-50)*.04,chem=(Number(e.chemistry||50)-50)*Number(a.chemistry||.025),tension=Number(e.tension||0)*Number(a.tension??-.055);return Math.round(clamp(Number(a.base||60)+skill+relation+bond+respect+chem+tension+diff,18,94))}
function canUse(a,s,e,name,u){const limit=Math.max(1,Number(cfg.activeInteractionsPerWeek||3));if(Number(u.used||0)>=limit)return[false,'Limit integracji na ten tydzień został wykorzystany.'];const last=Number(u.lastByUser?.[name]||0),cool=Math.max(0,Number(cfg.cooldownSameUserWeeks||1));if(last>0&&Number(s.turn||1)-last<cool)return[false,'Z tą osobą integrowałeś się już w tym tygodniu.'];if(a.requires&&!a.requires(e))return[false,a.locked||'Ta akcja nie jest jeszcze dostępna.'];return[true,'']}
function applyCareer(s,effects){const out={};for(const[k,raw]of Object.entries(effects||{})){let v=Number(raw)||0;if(!v)continue;v=Math.round(v*(.9+rand()*.2));if(!v)v=raw>0?1:-1;if(['reputation','activity','popularity','controversy','trust'].includes(k))s[k]=clamp(Number(s[k]||0)+v,0,100);else if(k==='score')s.score=Math.max(0,Number(s.score||0)+v);else continue;out[k]=v}return out}
function applySkills(s,effects){ensureSkills(s);const out={};for(const[k,raw]of Object.entries(effects||{})){if(!SKILLS[k])continue;let v=Math.round(Number(raw)||0);if(!v)continue;s.socialSkills[k]=clamp(Number(s.socialSkills[k]||45)+v,0,100);out[k]=v}return out}
function applyRel(e,effects){const out={};for(const[k,raw]of Object.entries(effects||{})){let v=Math.round(Number(raw)||0);if(!v)continue;if(k==='score')e.score=clamp(Number(e.score||0)+v,-100,100);else if(['bond','respect','chemistry','tension'].includes(k))e[k]=clamp(Number(e[k]||0)+v,0,100);else continue;out[k]=v}return out}
function deltaText(out,map){const a=[];for(const[k,v]of Object.entries(out||{}))a.push(`${map[k]||k} ${v>0?'+':''}${v}`);return a.join(' • ')||'bez zmian'}
const CAREER_NAMES={reputation:'REP',activity:'AKT',popularity:'POP',controversy:'KON',trust:'ZAU',score:'XP'};
const SKILL_NAMES={communication:'KOM',empathy:'EMP',teamwork:'WSP',humor:'HUM',assertiveness:'ASE'};
function addMemory(e,m){e.memories=Array.isArray(e.memories)?e.memories:[];e.memories.unshift(m);e.memories=e.memories.slice(0,Math.max(10,Number(cfg.relationMemoryLimit||40)))}
function perform(actionId,name){if(busy)return;const a=ACTIONS[actionId],s=state();if(!a||!s)return;ensureSkills(s);const d=relationData(s),e=d.users[name];if(!e)return;const u=usage(s),[allowed,reason]=canUse(a,s,e,name,u);if(!allowed){toast(reason);return}busy=true;try{const chance=chanceFor(a,s,e),success=rand()*100<chance,res=success?a.success:a.fail,relOut=applyRel(e,res.rel),careerOut=applyCareer(s,res.career),skillOut=applySkills(s,res.skills);e.interactions=Number(e.interactions||0)+1;e.manualInteractions=Number(e.manualInteractions||0)+1;e.trend=Number(relOut.score||0);e.lastTurn=Number(s.turn||1);e.actionCounts[actionId]=Number(e.actionCounts[actionId]||0)+1;addMemory(e,{turn:Number(s.turn||1),type:'manual',action:actionId,title:`${a.icon} ${a.name}`,success,detail:success?'Integracja zakończyła się dobrze i relacja dostała realny impuls.':'Integracja nie wyszła zgodnie z planem i zostawiła po sobie gorszą atmosferę.',relation:relOut.score||0,career:careerOut,skills:skillOut});u.used=Number(u.used||0)+1;u.lastByUser[name]=Number(s.turn||1);u.log.unshift({turn:Number(s.turn||1),user:name,action:actionId,success,chance,relation:relOut,career:careerOut,skills:skillOut,at:new Date().toISOString()});u.log=u.log.slice(0,120);saveRelations(s,d);saveUsage(s,u);s.relationInteractions=Math.max(0,Number(s.relationInteractions||0))+1;syncState(s);selected=name;lastRender='';renderExpanded(true);toast(success?`✅ Integracja z ${name} udana.`:`❌ Integracja z ${name} nie wyszła.`)}finally{busy=false}}
function toast(text){let e=$('#v715RelationToast');if(!e){e=document.createElement('div');e.id='v715RelationToast';e.className='v715-relation-toast';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function eventSkill(category,outcome){if(!['positive','negative'].includes(outcome))return null;const sign=outcome==='positive'?1:-1,cat=String(category||'').toUpperCase(),map={DRAMA:'empathy',MEMY:'humor','SPOŁECZNOŚĆ':'empathy',MODERACJA:'assertiveness',DYSKUSJA:'communication',EVENT:'teamwork',EKIPA:'teamwork','NOCNA MELINA':'communication',KULTURA:'humor',POZYCJA:'assertiveness',CHAOS:'communication',WKURW:'assertiveness'};const skill=map[cat]||'communication';return{[skill]:sign}}
function enrichLatestEvent(){const s=state();if(!s||!users.length||!Array.isArray(s.history)||!s.history.length)return;ensureSkills(s);const h=s.history[0],eventKey=`${h.turn}|${h.eventId}|${h.outcome}`,d=relationData(s);if(!d.processed.includes(eventKey)||d.v715Processed.includes(eventKey))return;const names=users.filter(n=>key(n)!==key(s.nickname)),seed=hash32(`${careerId(s)}|${eventKey}`),count=1+(seed%3),picked=[...names].sort((a,b)=>hash32(`${eventKey}|${a}`)-hash32(`${eventKey}|${b}`)).slice(0,count);for(const name of picked){const e=d.users[name];if(!e)continue;const rel=h.outcome==='positive'?{bond:2,respect:3,tension:-2}:h.outcome==='negative'?{bond:-1,respect:-2,tension:5}:{chemistry:((seed%3)-1),tension:((seed>>>4)%3)-1};const cat=String(h.category||'').toUpperCase();if(cat==='MEMY')rel.chemistry=(rel.chemistry||0)+(h.outcome==='positive'?3:-2);if(cat==='DRAMA')rel.tension=(rel.tension||0)+(h.outcome==='negative'?3:-1);if(cat==='SPOŁECZNOŚĆ')rel.bond=(rel.bond||0)+(h.outcome==='positive'?2:-1);if(cat==='MODERACJA'||cat==='POZYCJA')rel.respect=(rel.respect||0)+(h.outcome==='positive'?2:-1);applyRel(e,rel);addMemory(e,{turn:Number(h.turn||s.turn||1),type:'event',title:h.title||'Event',success:h.outcome==='positive',detail:h.outcome==='positive'?'Twoja decyzja podczas eventu poprawiła atmosferę tej relacji.':h.outcome==='negative'?'Twoja decyzja podczas eventu odbiła się negatywnie na tej relacji.':'Losowe zdarzenie lekko przesunęło dynamikę znajomości.',relation:Number(e.trend||0)})}const sd=eventSkill(h.category,h.outcome);if(sd)applySkills(s,sd);d.v715Processed.unshift(eventKey);d.v715Processed=d.v715Processed.slice(0,250);saveRelations(s,d);if(sd)syncState(s);lastRender=''}
function networkStats(d,s){const rows=Object.entries(d.users).filter(([n])=>key(n)!==key(s.nickname)).map(([name,e])=>({name,...e})),avg=rows.length?Math.round(rows.reduce((x,r)=>x+Number(r.score||0),0)/rows.length):0;return{rows,close:rows.filter(r=>r.score>=45).length,good:rows.filter(r=>r.score>=20).length,rivals:rows.filter(r=>r.score<=-40).length,avg}}
function tags(e){const t=[];if(e.bond>=70)t.push('💞 silna więź');if(e.respect>=70)t.push('🏅 wysoki szacunek');if(e.chemistry>=70)t.push('😂 świetna chemia');if(e.tension>=65)t.push('⚠️ wysokie napięcie');if(e.manualInteractions>=5)t.push('🔁 częsty kontakt');if(e.score<=-40)t.push('⚔️ konflikt');if(!t.length)t.push('🌱 relacja w budowie');return t}
function skillCard(k,v){const d=SKILLS[k];return`<div class="rel-skill-v715"><div><span>${d.icon} ${d.name}</span><b>${Math.round(v)}</b></div><div class="rel-skill-meter-v715"><i style="width:${clamp(v,0,100)}%"></i></div></div>`}
function relationCard(r){const[l,c]=relLabel(r.score);return`<button class="rel-user-card-v715 ${c} ${selected===r.name?'selected':''}" data-rel-user-select="${esc(r.name)}"><span class="rel-avatar-v715">${esc(r.name.slice(0,1).toUpperCase())}</span><span class="rel-user-copy-v715"><strong>${esc(r.name)}</strong><small>${l} • ${r.score>0?'+':''}${r.score}</small><span class="rel-line-v715"><i style="width:${(r.score+100)/2}%"></i></span><em>Więź ${r.bond} • Szacunek ${r.respect} • Napięcie ${r.tension}</em></span></button>`}
function actionCard(id,a,s,e,u){const chance=chanceFor(a,s,e),[ok,reason]=canUse(a,s,e,e.name,u),skillNames=(a.skills||[]).map(k=>SKILLS[k]?.name||k).join(' + ');return`<button class="rel-action-v715" data-rel-action-v715="${id}" data-rel-name-v715="${esc(e.name)}" ${ok?'':'disabled'}><span>${a.icon}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.desc)}</p><small>Szansa: <b>${chance}%</b> • rozwija: ${esc(skillNames||'relację')}</small>${!ok?`<em>${esc(reason)}</em>`:''}</div></button>`}
function memoryItem(m){const career=deltaText(m.career||{},CAREER_NAMES),skills=deltaText(m.skills||{},SKILL_NAMES);return`<div class="rel-memory-v715 ${m.success===false?'bad':''}"><span>TYDZ. ${m.turn||'—'}</span><div><strong>${esc(m.title||'Interakcja')}</strong><p>${esc(m.detail||'')}</p><small>${m.relation?`Relacja ${m.relation>0?'+':''}${m.relation}`:'Relacja bez bezpośredniej zmiany'}${career!=='bez zmian'?` • ${esc(career)}`:''}${skills!=='bez zmian'?` • ${esc(skills)}`:''}</small></div></div>`}
function detailHtml(s,e,u){if(!e)return'<div class="rel-empty-v715">Wybierz użytkownika z listy.</div>';const[l,c]=relLabel(e.score),limit=Number(cfg.activeInteractionsPerWeek||3),left=Math.max(0,limit-Number(u.used||0));return`<section class="rel-detail-v715 ${c}"><header><div class="rel-detail-avatar-v715">${esc(e.name.slice(0,1).toUpperCase())}</div><div><span>PROFIL RELACJI</span><h3>${esc(e.name)}</h3><p>${l} • <b>${e.score>0?'+':''}${e.score}</b> • ostatnia zmiana ${e.trend?`${e.trend>0?'+':''}${e.trend}`:'0'}</p></div><div class="rel-detail-limit-v715"><span>INTEGRACJE</span><b>${left}/${limit}</b><small>pozostało w tygodniu</small></div></header><div class="rel-dimensions-v715">${[['bond','💞 Więź'],['respect','🏅 Szacunek'],['chemistry','😂 Chemia'],['tension','⚠️ Napięcie']].map(([k,n])=>`<div><span>${n}</span><b>${e[k]}</b><div><i style="width:${e[k]}%"></i></div></div>`).join('')}</div><div class="rel-tags-v715">${tags(e).map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="rel-detail-stats-v715"><div><span>Wszystkie interakcje</span><b>${e.interactions}</b></div><div><span>Aktywne integracje</span><b>${e.manualInteractions||0}</b></div><div><span>Ostatni kontakt</span><b>${e.lastTurn?`tydz. ${e.lastTurn}`:'—'}</b></div></div><div class="rel-section-title-v715"><div><span>AKTYWNE INTEGRACJE</span><h4>Co chcesz zrobić?</h4></div><small>Każda akcja może podnieść albo obniżyć relację, parametry kariery i umiejętności społeczne.</small></div><div class="rel-actions-grid-v715">${Object.entries(ACTIONS).map(([id,a])=>actionCard(id,a,s,e,u)).join('')}</div><div class="rel-section-title-v715"><div><span>PAMIĘĆ RELACJI</span><h4>Ostatnie kontakty</h4></div></div><div class="rel-memory-list-v715">${e.memories?.length?e.memories.slice(0,8).map(memoryItem).join(''):'<div class="rel-empty-v715">Brak zapisanych wspólnych historii. Zacznij integrację albo rozegraj kolejne eventy.</div>'}</div></section>`}
function renderMini(){const s=state(),p=$('#relationsMiniV710');if(!s||!p||!users.length)return;const d=relationData(s),x=networkStats(d,s);p.innerHTML=`<div class="eyebrow">SIEĆ RELACJI • V7.15</div><h3>🤝 Twoje kontakty</h3><div class="rel-mini-grid"><div><b>${x.close}</b><span>Przyjaciele</span></div><div><b>${x.good}</b><span>Dobre kontakty</span></div><div><b>${x.rivals}</b><span>Konflikty</span></div></div><div class="rel-mini-network-v715"><span>Średnia relacja</span><b>${x.avg>0?'+':''}${x.avg}</b></div><button class="btn wide" id="openRelationsV710">OTWÓRZ ROZBUDOWANE RELACJE</button>`;$('#openRelationsV710').onclick=()=>{setTimeout(()=>renderExpanded(true),0);$('#relationsModalV710')?.classList.remove('hidden')}}
function renderExpanded(force=false){const modal=$('#relationsModalV710'),body=$('#relationsBodyV710'),s=state();if(!modal||!body||!s||!users.length)return;ensureSkills(s);const d=relationData(s),u=usage(s),stats=networkStats(d,s);let rows=stats.rows.sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'pl'));if(filter==='friends')rows=rows.filter(r=>r.score>=20);if(filter==='neutral')rows=rows.filter(r=>r.score>-20&&r.score<20);if(filter==='rivals')rows=rows.filter(r=>r.score<=-20);if(filter==='recent')rows=rows.sort((a,b)=>Number(b.lastTurn||0)-Number(a.lastTurn||0));if(query)rows=rows.filter(r=>key(r.name).includes(key(query)));if(!selected||!d.users[selected])selected=(rows[0]?.name||stats.rows[0]?.name||'');const sel=d.users[selected]?{name:selected,...d.users[selected]}:null,sig=[s.turn,u.used,filter,query,selected,localStorage.getItem(relKey(s)),JSON.stringify(s.socialSkills)].join('|');if(!force&&sig===lastRender&&body.querySelector('.relations-v715'))return;lastRender=sig;const limit=Number(cfg.activeInteractionsPerWeek||3);body.innerHTML=`<div class="relations-v715"><div class="rel-overview-v715"><div><span>BLISCY / PRZYJACIELE</span><b>${stats.close}</b></div><div><span>DOBRE KONTAKTY</span><b>${stats.good}</b></div><div><span>RYWALE / WROGOWIE</span><b>${stats.rivals}</b></div><div><span>ŚREDNIA SIECI</span><b>${stats.avg>0?'+':''}${stats.avg}</b></div><div class="accent"><span>INTEGRACJE W TYGODNIU</span><b>${u.used}/${limit}</b></div></div><div class="rel-skills-panel-v715"><div class="rel-section-title-v715"><div><span>UMIEJĘTNOŚCI SPOŁECZNE</span><h4>Twój rozwój w relacjach</h4></div><small>Umiejętności wpływają na powodzenie integracji i mogą rosnąć lub spadać po działaniach.</small></div><div class="rel-skills-grid-v715">${Object.entries(s.socialSkills).filter(([k])=>SKILLS[k]).map(([k,v])=>skillCard(k,v)).join('')}</div></div><div class="rel-toolbar-v715"><div class="rel-filters-v715">${[['all','Wszystkie'],['friends','Pozytywne'],['neutral','Neutralne'],['rivals','Konflikty'],['recent','Ostatnio aktywne']].map(([id,l])=>`<button data-rel-filter-v715="${id}" class="${filter===id?'active':''}">${l}</button>`).join('')}</div><label>🔎 <input id="relSearchV715" value="${esc(query)}" placeholder="Szukaj użytkownika…"></label></div><div class="rel-workspace-v715"><aside class="rel-users-v715">${rows.length?rows.map(relationCard).join(''):'<div class="rel-empty-v715">Brak użytkowników dla wybranego filtra.</div>'}</aside>${detailHtml(s,sel,u)}</div></div>`}
function handleClick(e){const f=e.target.closest('[data-rel-filter-v715]');if(f){filter=f.dataset.relFilterV715;lastRender='';renderExpanded(true);return}const u=e.target.closest('[data-rel-user-select]');if(u){selected=u.dataset.relUserSelect;lastRender='';renderExpanded(true);return}const a=e.target.closest('[data-rel-action-v715]');if(a&&!a.disabled){perform(a.dataset.relActionV715,a.dataset.relNameV715);return}const ch=e.target.closest('.relation-channel-v710,#openRelationsV710');if(ch)setTimeout(()=>renderExpanded(true),0)}
function handleInput(e){if(e.target.id==='relSearchV715'){query=e.target.value;lastRender='';renderExpanded(true);const input=$('#relSearchV715');if(input){input.focus();input.setSelectionRange(input.value.length,input.value.length)}}}
async function loadData(){try{const mr=await fetch(`${MANIFEST}?relations715=${Date.now()}`,{cache:'no-store'}),meta=mr.ok?await mr.json():{};cfg={...cfg,...(meta.relations||{})};const uf=meta.usersFile||'users.txt',ur=await fetch(`./data/${uf}?v=${encodeURIComponent(meta.databaseVersion||'0')}&t=${Date.now()}`,{cache:'no-store'});if(ur.ok)users=parseUsers(await ur.text())}catch(e){console.warn('Relations V7.15:',e)}}
function bootState(){const s=state();if(!s)return;const changed=ensureSkills(s);relationData(s);if(changed)syncState(s);renderMini()}
function tick(){const s=state();if(!s)return;enrichLatestEvent();renderMini();if(!$('#relationsModalV710')?.classList.contains('hidden'))renderExpanded()}
async function init(){await loadData();bootState();document.addEventListener('click',handleClick,true);document.addEventListener('input',handleInput);const modal=$('#relationsModalV710');if(modal)new MutationObserver(()=>{if(!modal.classList.contains('hidden'))setTimeout(()=>renderExpanded(true),0)}).observe(modal,{attributes:true,attributeFilter:['class']});setInterval(tick,700);const v=document.querySelector('.mini-user span');if(v)v.textContent='● online • V7.15'}
globalThis.MelonRelationsV715={open:()=>{const m=$('#relationsModalV710');if(m){m.classList.remove('hidden');renderExpanded(true)}},render:()=>renderExpanded(true),version:'7.15'};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
