(()=>{'use strict';
const AUTO='melon_auto_v5',MANIFEST='./data/database.json',REL_PREFIX='melon_relations_v710_',ACTION_PREFIX='melon_relation_actions_v714_';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cfg={activeInteractionsPerWeek:2,cooldownSameUserWeeks:1},busy=false;
const ACTIONS={
 voice:{icon:'🎙️',name:'Pogadaj na voice',desc:'Luźna rozmowa może zbudować kontakt, ale przy złym flow zrobi się niezręcznie.',base:78,success:{relation:6,effects:{trust:3,activity:3,score:18}},fail:{relation:-3,effects:{trust:-2,controversy:2,score:-5}}},
 game:{icon:'🎮',name:'Zagrajcie razem',desc:'Wspólna gra wzmacnia znajomość, dopóki wynik nie zacznie być ważniejszy od atmosfery.',base:70,success:{relation:7,effects:{activity:5,popularity:2,trust:2,score:24}},fail:{relation:-5,effects:{trust:-3,controversy:4,score:-10}}},
 project:{icon:'🛠️',name:'Zróbcie wspólny projekt',desc:'Największy potencjalny zysk, ale też spore ryzyko nieporozumień i dodatkowej roboty.',base:62,success:{relation:9,effects:{reputation:6,trust:5,activity:5,score:40}},fail:{relation:-6,effects:{activity:-3,trust:-4,controversy:5,score:-15}}},
 dm:{icon:'💬',name:'Pogadaj prywatnie',desc:'Spokojna rozmowa jeden na jeden zwykle poprawia relację, choć nie zawsze rozmowa się klei.',base:75,success:{relation:7,effects:{trust:5,reputation:2,score:18}},fail:{relation:-4,effects:{trust:-3,controversy:2,score:-5}}},
 meme:{icon:'😂',name:'Podeślij mema',desc:'Szybka próba złapania wspólnego humoru. Dobry mem łączy, fatalny bywa zapamiętany.',base:68,success:{relation:6,effects:{popularity:6,activity:3,score:22}},fail:{relation:-3,effects:{popularity:-2,controversy:3,score:-5}}},
 debate:{icon:'⚔️',name:'Wejdź w ostrą dyskusję',desc:'Ryzykowna integracja. Możesz zdobyć szacunek albo w kilka minut zbudować nową rywalizację.',base:54,success:{relation:3,effects:{reputation:5,activity:4,score:32}},fail:{relation:-9,effects:{controversy:8,trust:-5,reputation:-3,score:-18}}}
};
function json(k,f=null){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function state(){return globalThis.MelonCoreV714?.getState?.()||json(AUTO)}
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h>>>0}
function careerId(s){return String(s?.startProfileV79?.rolledAt||`${s?.nickname||'user'}|${s?.difficulty||'normal'}|${s?.startYear||2026}`)}
function relKey(s){return REL_PREFIX+hash32(careerId(s)).toString(36)}
function actionKey(s){return ACTION_PREFIX+hash32(careerId(s)).toString(36)}
function relLabel(v){if(v>=65)return'Przyjaciel';if(v>=35)return'Dobry kontakt';if(v>=12)return'Znajomy';if(v>-12)return'Neutralnie';if(v>-35)return'Chłodno';if(v>-65)return'Antagonista';return'Wróg'}
function rand(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}catch{return Math.random()}}
function currentUsage(s){const d=json(actionKey(s),{turn:Number(s.turn||1),used:0,lastByUser:{},log:[]});if(Number(d.turn)!==Number(s.turn||1)){d.turn=Number(s.turn||1);d.used=0}d.lastByUser=d.lastByUser||{};d.log=Array.isArray(d.log)?d.log:[];return d}
function saveUsage(s,d){localStorage.setItem(actionKey(s),JSON.stringify(d))}
function relationData(s){return json(relKey(s),{careerId:careerId(s),users:{},processed:[]})}
function relationFor(s,name){const d=relationData(s);return Number(d.users?.[name]?.score||0)}
function chanceFor(action,s,name){const r=relationFor(s,name),diff=s.difficulty==='hard'?-6:s.difficulty==='easy'?5:0;return Math.round(clamp(action.base+r*.12+diff,25,92))}
function applyEffects(s,effects){const out={};for(const[k,raw]of Object.entries(effects||{})){let v=Number(raw)||0;if(!v)continue;if(['reputation','activity','popularity','controversy','trust'].includes(k)){v=Math.round(v*(.85+rand()*.3));if(!v)v=raw>0?1:-1;s[k]=clamp(Number(s[k]||0)+v,0,100);out[k]=v}else if(k==='score'){v=Math.round(v*(.9+rand()*.2));s.score=Math.max(0,Number(s.score||0)+v);out[k]=v}}return out}
function effectText(out){const n={reputation:'REP',activity:'AKT',popularity:'POP',controversy:'KON',trust:'ZAU',score:'XP'};return Object.entries(out).map(([k,v])=>`${n[k]||k} ${v>0?'+':''}${v}`).join(' • ')||'bez zmian'}
function ensureModal(){if($('#relationActionModalV714'))return;const m=document.createElement('div');m.id='relationActionModalV714';m.className='modal hidden';m.innerHTML='<div class="modal-window relation-action-window-v714"><div class="modal-head"><div><div class="eyebrow">AKTYWNA INTEGRACJA • V7.14</div><h2 id="relationActionTitleV714">🤝 Integracja</h2></div><button class="close" data-rel714-close>×</button></div><div id="relationActionBodyV714"></div></div>';document.body.appendChild(m);m.querySelector('[data-rel714-close]').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')}}
function openActions(name){const s=state();if(!s)return;ensureModal();const usage=currentUsage(s),limit=Number(cfg.activeInteractionsPerWeek||2),used=Number(usage.used||0),rel=relationFor(s,name),last=Number(usage.lastByUser?.[name]||0),cool=Math.max(0,Number(cfg.cooldownSameUserWeeks||1)),blockedByUser=last>0&&Number(s.turn||1)-last<cool;$('#relationActionTitleV714').textContent=`🤝 ${name}`;$('#relationActionBodyV714').innerHTML=`<div class="relation-action-summary-v714"><div><span>RELACJA</span><b>${rel>0?'+':''}${rel} • ${relLabel(rel)}</b></div><div><span>INTEGRACJE W TYM TYGODNIU</span><b>${used}/${limit}</b></div></div>${blockedByUser?'<div class="relation-action-warning-v714">⏳ Z tym użytkownikiem integrowałeś się już bardzo niedawno. Poczekaj do kolejnego tygodnia.</div>':''}<div class="relation-action-grid-v714">${Object.entries(ACTIONS).map(([id,a])=>{const chance=chanceFor(a,s,name),disabled=used>=limit||blockedByUser;return`<button class="relation-action-card-v714" data-rel-action="${id}" data-rel-user="${esc(name)}" ${disabled?'disabled':''}><span class="relation-action-icon-v714">${a.icon}</span><div><strong>${esc(a.name)}</strong><p>${esc(a.desc)}</p><small>Szansa powodzenia: <b>${chance}%</b></small></div></button>`}).join('')}</div>${used>=limit?'<div class="relation-action-warning-v714">🚫 Wykorzystałeś limit aktywnych integracji na ten tydzień. Kolejne będą dostępne po rozegraniu następnego eventu.</div>':''}<div id="relationActionResultV714"></div>`;$('#relationActionModalV714').classList.remove('hidden')}
function refreshRelations(){setTimeout(()=>{const c=$('.relation-channel-v710');if(c)c.click()},80)}
function perform(id,name){if(busy)return;const s=state(),a=ACTIONS[id];if(!s||!a)return;const usage=currentUsage(s),limit=Number(cfg.activeInteractionsPerWeek||2);if(Number(usage.used||0)>=limit)return;const last=Number(usage.lastByUser?.[name]||0),cool=Math.max(0,Number(cfg.cooldownSameUserWeeks||1));if(last>0&&Number(s.turn||1)-last<cool)return;busy=true;try{const chance=chanceFor(a,s,name),success=rand()*100<chance,res=success?a.success:a.fail,out=applyEffects(s,res.effects),d=relationData(s),cur=d.users?.[name]||{score:0,interactions:0,trend:0,lastTurn:0},delta=Math.round(Number(res.relation||0)*(success?.9+rand()*.25:1));cur.score=clamp(Number(cur.score||0)+delta,-100,100);cur.interactions=Number(cur.interactions||0)+1;cur.trend=delta;cur.lastTurn=Number(s.turn||1);d.users=d.users||{};d.users[name]=cur;localStorage.setItem(relKey(s),JSON.stringify(d));usage.used=Number(usage.used||0)+1;usage.lastByUser=usage.lastByUser||{};usage.lastByUser[name]=Number(s.turn||1);usage.log.unshift({turn:Number(s.turn||1),user:name,action:id,success,chance,relationDelta:delta,effects:out,at:new Date().toISOString()});usage.log=usage.log.slice(0,100);saveUsage(s,usage);if(globalThis.MelonCoreV714?.replaceState)globalThis.MelonCoreV714.replaceState(s);else localStorage.setItem(AUTO,JSON.stringify(s));const box=$('#relationActionResultV714');if(box)box.innerHTML=`<div class="relation-action-result-v714 ${success?'success':'fail'}"><strong>${success?'✅ Integracja udana':'❌ Integracja nie wyszła'}</strong><p>${success?`Kontakt z ${esc(name)} rozwija się w dobrą stronę.`:`Rozmowa z ${esc(name)} zostawia po sobie więcej napięcia niż pożytku.`}</p><div>Relacja: <b>${delta>0?'+':''}${delta}</b> • ${esc(effectText(out))}</div></div>`;refreshRelations()}finally{busy=false}}
function decorate(){if(busy)return;const body=$('#relationsBodyV710');if(!body)return;const s=state();if(!s)return;const usage=currentUsage(s),limit=Number(cfg.activeInteractionsPerWeek||2);let bar=body.querySelector('.relation-actions-bar-v714');if(!bar){bar=document.createElement('div');bar.className='relation-actions-bar-v714';body.prepend(bar)}bar.innerHTML=`<div><span>🤝 AKTYWNE INTEGRACJE</span><strong>${usage.used}/${limit} w tym tygodniu</strong></div><small>Kliknij „INTEGRUJ” przy użytkowniku. Wynik może podnieść albo obniżyć relację oraz statystyki kariery.</small>`;body.querySelectorAll('.relation-card-v710').forEach(card=>{if(card.querySelector('.relation-integrate-v714'))return;const name=card.querySelector('strong')?.textContent?.trim();if(!name)return;const b=document.createElement('button');b.type='button';b.className='relation-integrate-v714';b.textContent='INTEGRUJ';b.onclick=e=>{e.preventDefault();e.stopPropagation();openActions(name)};card.appendChild(b)})}
function bind(){ensureModal();const body=$('#relationsBodyV710');if(body)new MutationObserver(()=>setTimeout(decorate,0)).observe(body,{childList:true,subtree:true});document.addEventListener('click',e=>{const b=e.target.closest('[data-rel-action]');if(b)perform(b.dataset.relAction,b.dataset.relUser)});setInterval(()=>{if(!$('#relationsModalV710')?.classList.contains('hidden'))decorate()},700)}
async function loadCfg(){try{const r=await fetch(`${MANIFEST}?relations714=${Date.now()}`,{cache:'no-store'});if(r.ok){const m=await r.json();cfg={...cfg,...(m.relations||{})}}catch(e){console.warn('Relations V7.14 config:',e)}}
async function init(){await loadCfg();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
