(()=>{'use strict';
const AUTO='melon_auto_v5',WALLET='melon_wallet_v74',MANIFEST='./data/database.json',GALA_STORE='melon_gala_categories_v710',REL_PREFIX='melon_relations_v710_';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SHOP={
 rep:{name:'Pakiet reputacji',cost:45,desc:'+6 reputacji',apply:s=>s.reputation=clamp(Number(s.reputation||0)+6,0,100)},
 trust:{name:'Akcja integracyjna',cost:50,desc:'+6 zaufania',apply:s=>s.trust=clamp(Number(s.trust||0)+6,0,100)},
 activity:{name:'Pakiet aktywności',cost:35,desc:'+8 aktywności',apply:s=>s.activity=clamp(Number(s.activity||0)+8,0,100)},
 drama:{name:'Tarcza antydrama',cost:55,desc:'-10 kontrowersyjności',apply:s=>s.controversy=clamp(Number(s.controversy||0)-10,0,100)},
 xp:{name:'Mentoring kariery',cost:75,desc:'+75 punktów / XP',apply:s=>{s.score=Math.max(0,Number(s.score||0)+75);s.level=Math.max(1,Math.floor(s.score/250)+1);s.bestLevel=Math.max(Number(s.bestLevel||1),s.level)}}
};
let users=[],categories=[],lastStateSig='',lastRelationEvent='',galaRendering=false;
function json(k,fallback=null){try{const v=JSON.parse(localStorage.getItem(k));return v??fallback}catch{return fallback}}
function state(){return json(AUTO)}
function saveState(s){localStorage.setItem(AUTO,JSON.stringify(s));localStorage.setItem(WALLET,String(Math.max(0,Math.round(Number(s.melons||0)))))}
function key(s=''){return String(s).trim().toLocaleLowerCase('pl')}
function hash32(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)>>>0}return h>>>0}
function careerId(s){return String(s?.startProfileV79?.rolledAt||`${s?.nickname||'user'}|${s?.difficulty||'normal'}|${s?.startYear||2026}`)}
function toast(text){let e=$('#v710Toast');if(!e){e=document.createElement('div');e.id='v710Toast';e.className='v710-toast';document.body.appendChild(e)}e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function parseUsers(t){const seen=new Set(),out=[];for(const raw of String(t).split(/\r?\n/)){const n=raw.trim();if(!n||n.startsWith('#')||n.startsWith('//'))continue;const k=key(n);if(seen.has(k))continue;seen.add(k);out.push(n)}return out}
function rand(){try{const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}catch{return Math.random()}}
function randint(a,b){return Math.floor(rand()*(b-a+1))+a}
function weightedPick(items,weightFn){const w=items.map(x=>Math.max(.001,Number(weightFn(x))||.001)),sum=w.reduce((a,b)=>a+b,0);let r=rand()*sum;for(let i=0;i<items.length;i++){r-=w[i];if(r<=0)return items[i]}return items.at(-1)}
function weightedSample(items,n,weightFn){const pool=[...items],out=[];while(pool.length&&out.length<n){const x=weightedPick(pool,weightFn);out.push(x);pool.splice(pool.indexOf(x),1)}return out}
function activityPower(s){if(!s)return 1;const activity=clamp(Number(s.activity||0),0,100),level=Math.max(1,Number(s.level||1)),streak=Math.max(0,Number(s.streak||0));return Math.round(clamp(1+(activity/100)*.8+Math.max(0,level-1)*.06+Math.min(streak,10)*.02,1,2.8)*100)/100}
function activityTier(s){const a=Number(s?.activity||0),l=Number(s?.level||1);if(a>=90&&l>=10)return['IKONA AKTYWNOŚCI','🌟'];if(a>=80&&l>=8)return['GŁOS SERWERA','🎙️'];if(a>=65&&l>=5)return['STAŁY BYWALEC','🔥'];if(a>=50)return['AKTYWNY','⚡'];if(a>=30)return['OBECNY','🟢'];return['UŚPIONY','🌙']}
async function loadData(){try{const mr=await fetch(`${MANIFEST}?v710=${Date.now()}`,{cache:'no-store'}),meta=mr.ok?await mr.json():{};const uf=meta.usersFile||'users.txt',gf=meta.goldenMelonsCategoriesFile||'golden-melons-v710.json';const [ur,gr]=await Promise.all([fetch(`./data/${uf}?t=${Date.now()}`,{cache:'no-store'}),fetch(`./data/${gf}?t=${Date.now()}`,{cache:'no-store'})]);if(ur.ok)users=parseUsers(await ur.text());if(gr.ok){const x=await gr.json();if(Array.isArray(x))categories=x}}catch(e){console.warn('V7.10 data:',e)}}

/* SKLEP: przechwytujemy stary onclick zanim wykona reload. */
function syncMainEngine(s){const input=$('#importSaveInput');if(!input||typeof DataTransfer==='undefined'||typeof File==='undefined')return false;try{const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(s)],'v710-shop-sync.json',{type:'application/json'}));input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return true}catch(e){console.warn('V7.10 shop sync:',e);return false}}
function refreshShop(){setTimeout(()=>{const ch=$('.channel[data-nav="shop"]');if(ch)ch.click();renderActivityCard();renderRelationsMini()},180)}
function buyFixed(id){const item=SHOP[id],s=state();if(!item||!s)return;const wallet=Math.max(0,Number(s.melons??localStorage.getItem(WALLET)??0));if(wallet<item.cost)return toast('Masz za mało Melonów.');s.melons=wallet-item.cost;item.apply(s);saveState(s);const synced=syncMainEngine(s);toast(`✅ ${item.name}: ${item.desc}. Saldo: ${s.melons} 🍉`);if(synced)refreshShop();else{updateVisibleStats(s);refreshShop()}}
function updateVisibleStats(s){const map={moneyValue:s.melons,scoreValue:s.score,levelValue:s.level};for(const[id,v]of Object.entries(map)){const e=$('#'+id);if(e)e.textContent=v}const bars=$('#statsBars');if(bars){const labels={reputation:'Reputacja',activity:'Aktywność',popularity:'Rozpoznawalność',controversy:'Kontrowersyjność',trust:'Zaufanie'};bars.innerHTML=Object.entries(labels).map(([k,l])=>`<div><div class="barhead"><span>${l}</span><b>${Math.round(s[k]||0)}</b></div><div class="bar"><div style="width:${clamp(Number(s[k]||0),0,100)}%"></div></div></div>`).join('')}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-shop]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();buyFixed(b.dataset.shop)},true);

/* 1 event = 1 tydzień. Automatyczny event zastępuje zwykły event tego tygodnia. */
function weeklyBadge(){let b=$('#weeklyPolicyV710');if(!b){const turn=$('.panel.turn');if(!turn)return;b=document.createElement('div');b.id='weeklyPolicyV710';b.className='weekly-policy-v710';turn.appendChild(b)}b.innerHTML='<span>🎲 1 EVENT / TYDZIEŃ</span><small>Każdy tydzień losuje jeden event: zwykły albo automatyczny.</small>'}

/* RELACJE Z UŻYTKOWNIKAMI */
function relStorageKey(s){return REL_PREFIX+hash32(careerId(s)).toString(36)}
function relLabel(v){if(v>=65)return['Przyjaciel','best'];if(v>=35)return['Dobry kontakt','good'];if(v>=12)return['Znajomy','warm'];if(v>-12)return['Neutralnie','neutral'];if(v>-35)return['Chłodno','cold'];if(v>-65)return['Antagonista','rival'];return['Wróg','enemy']}
function ensureRelations(s){if(!s||!users.length)return null;const k=relStorageKey(s),data=json(k,{careerId:careerId(s),users:{},processed:[]});for(const name of users){if(key(name)===key(s.nickname))continue;if(!data.users[name]){const seed=hash32(`${careerId(s)}|${name}`);data.users[name]={score:(seed%25)-12,interactions:0,trend:0,lastTurn:0}}}localStorage.setItem(k,JSON.stringify(data));return data}
function processRelationEvent(s){if(!s||!users.length||!Array.isArray(s.history)||!s.history.length)return;const h=s.history[0],eventKey=`${h.turn}|${h.eventId}|${h.outcome}`;if(eventKey===lastRelationEvent)return;lastRelationEvent=eventKey;const k=relStorageKey(s),data=ensureRelations(s);if(!data||data.processed.includes(eventKey))return;const names=users.filter(n=>key(n)!==key(s.nickname));if(!names.length)return;const seed=hash32(`${careerId(s)}|${eventKey}`),count=1+(seed%3);const picked=[...names].sort((a,b)=>(hash32(`${eventKey}|${a}`)-hash32(`${eventKey}|${b}`))).slice(0,count);for(let i=0;i<picked.length;i++){const name=picked[i],r=data.users[name]||{score:0,interactions:0,trend:0,lastTurn:0};let delta;if(h.outcome==='positive')delta=1+((seed>>>(i*3))%5);else if(h.outcome==='negative')delta=-(1+((seed>>>(i*3))%5));else delta=((seed>>>(i*3))%5)-2;r.score=clamp(Number(r.score||0)+delta,-100,100);r.interactions=Number(r.interactions||0)+1;r.trend=delta;r.lastTurn=Number(h.turn||s.turn||1);data.users[name]=r}data.processed.unshift(eventKey);data.processed=data.processed.slice(0,250);localStorage.setItem(k,JSON.stringify(data));renderRelationsMini();if(!$('#relationsModalV710')?.classList.contains('hidden'))renderRelationsModal()}
function relationStats(s){const d=ensureRelations(s);if(!d)return{friends:0,rivals:0,neutral:0,total:0};const vals=users.filter(n=>d.users[n]&&key(n)!==key(s.nickname)).map(n=>d.users[n].score);return{friends:vals.filter(v=>v>=35).length,rivals:vals.filter(v=>v<=-35).length,neutral:vals.filter(v=>v>-12&&v<12).length,total:vals.length}}
function ensureRelationUi(){if(!$('.channel[data-v710-rel]')){const stats=$$('.channel').find(x=>x.textContent.trim()==='statystyki');if(stats){const c=document.createElement('div');c.className='channel relation-channel-v710';c.dataset.v710Rel='1';c.setAttribute('role','button');c.tabIndex=0;c.textContent='relacje';stats.insertAdjacentElement('afterend',c);c.onclick=openRelations;c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openRelations()}}}}
 if(!$('#relationsModalV710')){const m=document.createElement('div');m.id='relationsModalV710';m.className='modal hidden';m.innerHTML='<div class="modal-window relations-window-v710"><div class="modal-head"><div><div class="eyebrow">SIEĆ SPOŁECZNOŚCIOWA • V7.10</div><h2>🤝 Relacje z użytkownikami</h2></div><button class="close" data-rel-close>×</button></div><div id="relationsBodyV710"></div></div>';document.body.appendChild(m);m.querySelector('[data-rel-close]').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')}}}
function renderRelationsMini(){const s=state();if(!s)return;ensureRelationUi();let p=$('#relationsMiniV710');if(!p){const target=$('.panel.stats');if(!target)return;p=document.createElement('div');p.id='relationsMiniV710';p.className='panel relations-mini-v710';target.insertAdjacentElement('afterend',p)}const x=relationStats(s);p.innerHTML=`<div class="eyebrow">SIEĆ RELACJI</div><h3>🤝 Twoje kontakty</h3><div class="rel-mini-grid"><div><b>${x.friends}</b><span>Dobre relacje</span></div><div><b>${x.neutral}</b><span>Neutralne</span></div><div><b>${x.rivals}</b><span>Rywalizacje</span></div></div><button class="btn wide" id="openRelationsV710">OTWÓRZ RELACJE</button>`;$('#openRelationsV710').onclick=openRelations}
function openRelations(){ensureRelationUi();renderRelationsModal();$('#relationsModalV710').classList.remove('hidden')}
function renderRelationsModal(){const s=state(),body=$('#relationsBodyV710');if(!body)return;if(!s){body.innerHTML='<div class="hint">Rozpocznij karierę, aby budować relacje.</div>';return}const d=ensureRelations(s);if(!d){body.innerHTML='<div class="hint">Lista users.txt nie jest jeszcze dostępna.</div>';return}const rows=users.filter(n=>d.users[n]&&key(n)!==key(s.nickname)).map(n=>({name:n,...d.users[n]})).sort((a,b)=>b.score-a.score);body.innerHTML=`<div class="relations-summary-v710"><div><span>Użytkownicy w sieci</span><b>${rows.length}</b></div><div><span>Najlepszy kontakt</span><b>${esc(rows[0]?.name||'—')}</b></div><div><span>Najtrudniejsza relacja</span><b>${esc(rows.at(-1)?.name||'—')}</b></div></div><div class="relations-grid-v710">${rows.map(r=>{const[l,c]=relLabel(r.score);return`<article class="relation-card-v710 ${c}"><div class="relation-avatar-v710">${esc(r.name.slice(0,1).toUpperCase())}</div><div class="relation-copy-v710"><strong>${esc(r.name)}</strong><span>${l} • ${r.score>0?'+':''}${r.score}</span><div class="relation-meter-v710"><i style="width:${(r.score+100)/2}%"></i></div><small>${r.interactions} interakcji${r.trend?` • ostatnio ${r.trend>0?'+':''}${r.trend}`:''}</small></div></article>`}).join('')}</div>`}

/* AKTYWNOŚĆ I SZANSA NA ZŁOTEGO MELONA */
function renderActivityCard(){const s=state();if(!s)return;let p=$('#activitySystemV710');if(!p){const side=$('.col.side');if(!side)return;p=document.createElement('div');p.id='activitySystemV710';p.className='panel activity-system-v710';const gala=$('.golden-melons-card');(gala||side.firstElementChild)?.insertAdjacentElement(gala?'beforebegin':'afterend',p)}const[tier,icon]=activityTier(s),power=activityPower(s),isListed=users.some(n=>key(n)===key(s.nickname));p.innerHTML=`<div class="activity-orb-v710">${icon}</div><div><div class="eyebrow">AKTYWNOŚĆ GALOWA</div><h3>${tier}</h3><p>Aktywność <b>${Math.round(s.activity||0)}</b> • LVL <b>${s.level||1}</b> • seria <b>${s.streak||0}</b></p><div class="activity-power-v710"><span>Mnożnik szans na nominację</span><strong>×${power.toFixed(2)}</strong></div><small>${isListed?'Twój nick jest w users.txt — bonus działa podczas Złotych Melonów.':'Dodaj swój nick do users.txt, aby bonus mógł działać w gali.'}</small></div>`}

/* 10 KATEGORII ZŁOTYCH MELONÓW */
function galaRoot(){const s=state();if(!s)return null;const root=json(GALA_STORE,{}),cid=careerId(s);root[cid]=root[cid]||{};return{root,cid,s}}
function galaWeight(name,s){return key(name)===key(s.nickname)?activityPower(s):1}
function generateCategoryAwards(year){const x=galaRoot();if(!x||users.length<3||!categories.length)return null;const{root,cid,s}=x;if(root[cid][year])return root[cid][year];const wins={};const awards=[];for(const cat of categories){const nominees=weightedSample(users,3,n=>galaWeight(n,s));const winner=weightedPick(nominees,n=>galaWeight(n,s)*Math.pow(.58,wins[key(n)]||0));wins[key(winner)]=(wins[key(winner)]||0)+1;const raw=nominees.map(n=>({name:n,x:(.65+rand()*.7)*galaWeight(n,s)*(key(n)===key(winner)?1.35:1)})),sum=raw.reduce((a,b)=>a+b.x,0);let results=raw.map(r=>({name:r.name,percent:Math.round(r.x/sum*1000)/10})).sort((a,b)=>b.percent-a.percent);const diff=Math.round((100-results.reduce((a,b)=>a+b.percent,0))*10)/10;results[0].percent=Math.round((results[0].percent+diff)*10)/10;awards.push({...cat,nominees,winner,results})}root[cid][year]={year,generatedAt:new Date().toISOString(),activityPower:activityPower(s),awards};localStorage.setItem(GALA_STORE,JSON.stringify(root));return root[cid][year]}
function currentYear(s){return 2026+Math.floor((Math.max(1,Number(s?.turn||1))-1)/52)}
function ensureGalaAwards(){const s=state();if(!s)return;for(const y of Object.keys(s.galas||{})){if(s.galas[y])generateCategoryAwards(Number(y))}}
function renderGalaV710(){if(galaRendering)return;const modal=$('#goldenMelonsModal'),results=$('#galaResults'),s=state();if(!modal||!results||!s)return;const y=Number($('#galaModalYear')?.textContent)||currentYear(s),hasBase=!!s.galas?.[y],award=hasBase?generateCategoryAwards(y):null;const heading=results.closest('section')?.querySelector('h3');if(heading)heading.textContent='KATEGORIE ZŁOTYCH MELONÓW';galaRendering=true;if(!hasBase){results.innerHTML=`<div class="gala-preview-v710"><div class="gala-preview-head-v710"><span>🏆 ${categories.length||10} kategorii</span><b>Losowanie w 52. tygodniu</b></div><div class="gala-category-preview-grid-v710">${categories.map(c=>`<div class="gala-category-pill-v710 tone-${esc(c.tone)}"><span>${c.icon}</span><strong>${esc(c.name)}</strong><small>${esc(c.description)}</small></div>`).join('')}</div><div class="hint">Każda kategoria otrzyma 3 nominowanych i 1 zwycięzcę. Aktywność oraz poziom zwiększają szansę aktywnego gracza, jeżeli jego nick znajduje się w users.txt.</div></div>`}else if(award){results.innerHTML=`<div class="gala-v710-summary"><div><span>EDYCJA</span><b>${y}</b></div><div><span>KATEGORIE</span><b>${award.awards.length}</b></div><div><span>MNOŻNIK AKTYWNOŚCI</span><b>×${Number(award.activityPower||1).toFixed(2)}</b></div></div><div class="gala-awards-grid-v710">${award.awards.map(a=>`<article class="gala-award-v710 tone-${esc(a.tone)}"><header><span>${a.icon}</span><div><small>ZŁOTY MELON</small><h3>${esc(a.name)}</h3></div></header><div class="gala-winner-v710">🏆 <strong>${esc(a.winner)}</strong></div><div class="gala-nominees-v710">${a.results.map(r=>`<div class="${key(r.name)===key(a.winner)?'winner':''}"><span>${esc(r.name)}</span><b>${Number(r.percent).toFixed(1)}%</b></div>`).join('')}</div></article>`).join('')}</div>`}const status=$('#goldenMelonsStatus');if(status)status.textContent=hasBase?`Gala ${y} zakończona • ${award?.awards?.length||categories.length} kategorii Złotych Melonów.`:`Gala uruchomi się automatycznie w 52. tygodniu • ${categories.length||10} kategorii • baza ${users.length} użytkowników.`;setTimeout(()=>{galaRendering=false},0)}

function stateSignature(s){return s?`${s.turn}|${s.eventCount}|${s.activity}|${s.level}|${s.streak}|${s.melons}|${Object.keys(s.galas||{}).join(',')}`:''}
function tick(){const s=state();weeklyBadge();ensureRelationUi();if(s){const sig=stateSignature(s);if(sig!==lastStateSig){lastStateSig=sig;ensureRelations(s);processRelationEvent(s);renderActivityCard();renderRelationsMini();ensureGalaAwards()}if(!$('#goldenMelonsModal')?.classList.contains('hidden'))renderGalaV710()}const ver=$('.mini-user span');if(ver)ver.textContent='● online • V7.10'}
async function init(){await loadData();weeklyBadge();ensureRelationUi();const s=state();if(s){ensureRelations(s);renderActivityCard();renderRelationsMini();ensureGalaAwards()}setInterval(tick,500);document.addEventListener('click',e=>{if(e.target.closest('#goldenMelonsBtn'))setTimeout(renderGalaV710,120)});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js?v=7.10.0').catch(()=>{})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
